// mss-app-react/src/components/noTVGames/NoTvGamesTable.tsx
import { formatWeekday } from '#utils/dateFormatting.mjs';
import React, { useMemo } from 'react';

interface NoTvGame {
  gameTitle?: string;
  visitingTeam: string;
  homeTeam: string;
  location?: string;
  conference: string;
  tvOptions: string;
  timeWithOffset: string;
  fcs?: string;
}

interface Props {
  noTvDate: string;
  noTvGamesForDate: NoTvGame[];
}

const NoTvGamesTable: React.FC<Props> = ({ noTvDate, noTvGamesForDate }) => {
  const formattedDate = useMemo(() => formatWeekday(noTvDate), [noTvDate]);

  return (
    <div style={{ marginBottom: '30px' }}>
      <h3 style={{ marginBottom: '15px' }}>{formattedDate}</h3>
      <table
        style={{
          width: '100%',
          borderCollapse: 'collapse',
          backgroundColor: '#fff',
          border: '2px ridge #fff',
          borderSpacing: '1px'
        }}
      >
        <thead>
          <tr style={{ textAlign: 'center' }}>
            <th style={{ padding: '8px', border: '1px solid gray' }}>Game</th>
            <th style={{ padding: '8px', border: '1px solid gray' }}>Conference</th>
            <th style={{ padding: '8px', border: '1px solid gray' }}>Television Options</th>
          </tr>
        </thead>
        <tbody>
          {noTvGamesForDate.map((game, index) => (
            <tr
              key={index}
              style={{
                backgroundColor: game.fcs ? '#ffff00' : 'transparent'
              }}
            >
              <td
                style={{
                  width: '243px',
                  padding: '2px',
                  border: '1px solid gray',
                  textAlign: 'left'
                }}
              >
                {game.gameTitle && (
                  <>
                    <span style={{ fontWeight: 'bold', fontStyle: 'italic' }}>{game.gameTitle}</span>
                    <br />
                  </>
                )}
                {game.location ? (
                  <>
                    {game.visitingTeam} vs. {game.homeTeam}
                    <br />
                    (at {game.location})
                  </>
                ) : (
                  <>
                    {game.visitingTeam} at {game.homeTeam}
                    <br />
                  </>
                )}
              </td>
              <td
                style={{
                  width: '100px',
                  padding: '5px',
                  border: '1px solid gray',
                  textAlign: 'center'
                }}
              >
                {game.conference}
              </td>
              <td
                style={{
                  width: '400px',
                  padding: '5px',
                  border: '1px solid gray',
                  textAlign: 'center'
                }}
              >
                {game.tvOptions}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

export default NoTvGamesTable;

// mss-app/src/components/noTVGames/NoTvGamesTable.vue
<script setup lang="ts">
import type { NoTvGame } from '@/graphQl';
import { updatedTvOptions } from '@/utils';
import { DateTime } from 'luxon';
import { computed } from 'vue';

const props = defineProps<{ noTvGamesForDate: NoTvGame[]; noTvDate: string }>();
const { noTvGamesForDate, noTvDate } = props;

const formattedDate = computed(() => DateTime.fromISO(noTvDate).toFormat('DDDD'));
</script>

<template>
  <div>
    <h3>{{ formattedDate }}</h3>
    <table class="noTVTable">
      <thead>
        <tr class="header">
          <th>Game</th>
          <th>Conference</th>
          <th>Television Options</th>
        </tr>
      </thead>
      <tbody>
        <tr
          v-for="(noTvGameForDate, index) in noTvGamesForDate"
          :key="index"
          :class="{ fcsgame: noTvGameForDate.fcs }"
        >
          <td class="game">
            <template v-if="noTvGameForDate.gameTitle">
              <b><i>{{ noTvGameForDate.gameTitle }}</i></b><br>
            </template>
            <template v-if="noTvGameForDate.location">
              <template v-if="noTvGameForDate.visitingTeam">
                {{ noTvGameForDate.visitingTeam }} vs. {{ noTvGameForDate.homeTeam }}<br>
              </template>
              (at {{ noTvGameForDate.location }})
            </template>
            <template v-else>
              <template v-if="noTvGameForDate.visitingTeam">
                {{ noTvGameForDate.visitingTeam }} at {{ noTvGameForDate.homeTeam }}<br>
              </template>
            </template>
          </td>
          <td class="conference">
            {{ noTvGameForDate.conference }}
          </td>
          <td class="telecast">
            {{ updatedTvOptions(noTvGameForDate) }}
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<style scoped>
.fcsgame {
  background-color: #ff0;
}

.game,
.conference,
.telecast {
  border: medium solid Gray;
  border-width: thin;
}

.noTVTable {
  background-color: #fff;
  border: 2px ridge #fff;
  border-spacing: 1px;
  border-collapse: collapse;
  font-family: Arial;
}

.conference,
.telecast {
  text-align: center;
  padding: 5px;
}

.game {
  width: 243px;
}

.conference {
  width: 100px;
}

.telecast {
  width: 400px;
}

@media all and (min-width: 641px) {
  .game {
    padding: 2px;
  }
}

@media only screen and (max-width: 640px) {
  .game {
    padding: 1px;
  }
}
</style>
