// mss-app-react/src/components/weeklyText/WeekTextSchedule.tsx
import { useResetAdsenseHeight, useWeekScheduleNav, useWeekTextSchedule } from '#hooks/index.mjs';
import { LazyAdsByGoogle, LazyBackToTop, LazyCopyrightLink } from '#shared/lazyIndex.tsx';
import { WeekTextBase, type WeekTextTableHandle } from '#text/index.tsx';
import React, { Suspense, useMemo, useRef } from 'react';
import { Link } from 'react-router-dom';
import styles from './WeekTextSchedule.module.css';

interface WeekTextScheduleProps {
  week: string;
  sport: string;
  paramYear: string;
}

const WeekTextSchedule: React.FC<WeekTextScheduleProps> = ({ week, sport, paramYear }) => {
  const mainRef = useResetAdsenseHeight();

  const tableRef = useRef<WeekTextTableHandle | null>(null);

  const year = useMemo(() => {
    return sport === 'football' ? paramYear : `${paramYear.slice(0, 4)}${paramYear.slice(5)}`;
  }, [sport, paramYear]);

  const weekInt = useMemo(() => parseInt(week), [week]);

  const {
    seasonContentsResult,
    seasonContentsLoading,
    seasonContentsError,
    nextWeek,
    previousWeek,
    isBowlWeek,
    isMbkPostseason,
    isWeekOne,
    isNextWeekMbkPostseason,
    isNextWeekBowlWeek,
  } = useWeekScheduleNav(sport, year, weekInt);

  const { tvGameResult, tvGameLoading, tvGameError } = useWeekTextSchedule(sport, year, weekInt);

  const isLoading = seasonContentsLoading || tvGameLoading;
  const isError = seasonContentsError || tvGameError;

  if (isError) {
    return (
      <div className={styles.errorContainer}>
        <p>Sorry. Got a bit of a problem. Let Matt know.</p>
      </div>
    );
  }

  if (isLoading || !seasonContentsResult || !tvGameResult) {
    return (
      <div className={styles.loadingContainer}>
        <p className={styles.loadingText}>
          Loading Week {week} for {paramYear}
        </p>
      </div>
    );
  }

  return (
    <main ref={mainRef as React.RefObject<HTMLMapElement | null>}>
      <nav role="navigation" className={`${styles.navbar} DONTPrint`}>
        <div className={styles.container}>
          <div className={styles.flexContainer}>
            <div className={styles.flexRow}>
              <Link to="/">Home</Link>
            </div>
            <div className={styles.flexRow}>
              <Link to={`/season/${sport}/${paramYear}`}>Season Home</Link>
            </div>
            <div className={styles.flexRow}>
              <Link className="DONTPrint" to={`/schedule/${sport}/${paramYear}/${week}`}>
                Weekly Schedule
              </Link>
            </div>
          </div>

          {!isMbkPostseason && !isBowlWeek && (
            <div className={`${styles.flexContainerRow} ${styles.pad}`}>
              {isWeekOne ? (
                <div className={styles.flexRowLeft}>
                  <Link to={`/schedule/${sport}/${paramYear}/${nextWeek}/text`}>Next Week</Link>
                </div>
              ) : (
                <>
                  <div className={styles.flexRowLeft}>
                    <Link to={`/schedule/${sport}/${paramYear}/${previousWeek}/text`}>Previous Week</Link>
                  </div>
                  {!isNextWeekMbkPostseason && !isNextWeekBowlWeek && (
                    <div className={styles.flexRowRight}>
                      <Link to={`/schedule/${sport}/${paramYear}/${nextWeek}/text`}>Next Week</Link>
                    </div>
                  )}
                </>
              )}
              <br className={styles.mobilehide} />
            </div>
          )}
          <br />

          <p id="TextNav" className={`${styles.TextNav} DONTPrint`}>
            <button
              id="ClearAll"
              type="button"
              className={`${styles.inputpad} ${styles.buttonfont}`}
              onClick={() => tableRef.current?.clearAll()}
            >
              Clear All Games
            </button>

            <button
              id="CheckAll"
              type="button"
              className={`${styles.inputpad} ${styles.buttonfont}`}
              onClick={() => tableRef.current?.checkAll()}
            >
              Check All Games
            </button>
          </p>
        </div>
      </nav>

      <WeekTextBase
        ref={tableRef}
        season={year}
        tvGames={tvGameResult.tvGames!.tvGames}
        isBowlWeek={isBowlWeek}
        isMbkPostseason={isMbkPostseason}
        showPpvColumn={tvGameResult.tvGames!.showPPVColumn}
      />

      <Suspense fallback={null}>
        <LazyBackToTop />
        <LazyAdsByGoogle />
        <LazyCopyrightLink />
      </Suspense>
    </main>
  );
};

export default WeekTextSchedule;

// mss-app/src/components/weeklyText/WeekTextSchedule.vue
<script setup lang="ts">
import { useWeekScheduleNav } from '#composables/useWeekScheduleNav.mjs';
import { useWeekTextSchedule } from '#composables/useWeekTextSchedule.mjs';
import AdsByGoogle from '#shared/AdsByGoogle.vue';
import BackToTop from '#shared/BackToTop.vue';
import Copyright from '#shared/CopyrightLink.vue';
import WeekTextBase from '#text/WeekTextBase.vue';
import { checkAllTextRows, clearAllSelectedTextRows } from '#utils/domText.mjs';
import { computed } from 'vue';

const props = defineProps<{ week: string; sport: string; paramYear: string }>();
const { week, sport, paramYear } = props;

const year = computed(() => (sport === 'football' ? paramYear : `${paramYear.slice(0, 4)}${paramYear.slice(5)}`));

const weekInt = computed(() => parseInt(week));

const {
  seasonContentsResult,
  seasonContentsLoading,
  seasonContentsError,
  nextWeek,
  previousWeek,
  isBowlWeek,
  isMbkPostseason,
  isWeekOne,
  isNextWeekMbkPostseason,
  isNextWeekBowlWeek
} = useWeekScheduleNav(sport, year.value, weekInt.value);

const { tvGameResult, tvGameLoading, tvGameError } = useWeekTextSchedule(sport, year.value, weekInt.value);
</script>

<template>
  <div>
    <template v-if="seasonContentsLoading || tvGameLoading">
      <div class="loading-container">
        <p class="loading-text">Loading Week {{ week }} for {{ paramYear }}</p>
      </div>
    </template>
    <template v-if="seasonContentsError || tvGameError">
      <div class="error-container">
        <p>Sorry. Got a bit of a problem. Let Matt know.</p>
      </div>
    </template>
    <template v-if="seasonContentsResult && tvGameResult">
      <nav role="navigation" class="navbar DONTPrint">
        <div class="container">
          <div class="flex-container">
            <div class="flex-row">
              <RouterLink to="/">Home</RouterLink>
            </div>
            <div class="flex-row">
              <RouterLink :to="`/season/${sport}/${paramYear}`">Season Home</RouterLink>
            </div>
            <div class="flex-row">
              <RouterLink class="DONTPrint" :to="`/schedule/${sport}/${paramYear}/${week}`">
                Weekly Schedule
              </RouterLink>
            </div>
          </div>
          <div v-if="!isMbkPostseason && !isBowlWeek" class="flex-container-row pad">
            <template v-if="isWeekOne">
              <div class="flex-row-left">
                <RouterLink :to="{ path: `/schedule/${sport}/${paramYear}/${nextWeek}` }">Next Week</RouterLink>
              </div>
            </template>
            <template v-else>
              <div class="flex-row-left">
                <RouterLink :to="{ path: `/schedule/${sport}/${paramYear}/${previousWeek}/text` }"
                  >Previous Week
                </RouterLink>
              </div>
              <div v-if="!isNextWeekMbkPostseason && !isNextWeekBowlWeek" class="flex-row-right">
                <RouterLink :to="{ path: `/schedule/${sport}/${paramYear}/${nextWeek}/text` }">Next Week </RouterLink>
              </div>
            </template>
            <br class="mobilehide" />
          </div>
          <br />
          <p id="TextNav" class="DONTPrint">
            <button id="ClearAll" class="inputpad buttonfont" @click="clearAllSelectedTextRows">Clear All Games</button>

            <button id="CheckAll" class="inputpad buttonfont" @click="checkAllTextRows">Check All Games</button>
          </p>
        </div>
      </nav>
    </template>

    <template v-if="tvGameResult">
      <WeekTextBase
        :season="year"
        :tv-games="tvGameResult.tvGames.tvGames"
        :is-bowl-week="isBowlWeek"
        :is-mbk-postseason="isMbkPostseason"
        :show-ppv-column="tvGameResult.tvGames.showPPVColumn" />
      <BackToTop />
      <AdsByGoogle />
      <Copyright />
    </template>
  </div>
</template>

<style scoped>
.inputpad {
  padding-left: 10px;
  margin-right: 3px;
}

.container {
  height: 100%;
  max-width: 800px;
  margin: 0 auto;
}

#TextNav {
  margin: 0;
}

.navbar {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  z-index: 9999;
  width: 100%;
  background-color: white;
  padding: 2px 0;
  box-shadow: 0 1px 1px rgba(0, 0, 0, 0.1);
  display: block;
  align-items: center;
  height: 119.5px;
}

.pad {
  padding: 5px 0;
}

.loading-container,
.error-container {
  min-height: 200px;
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  max-width: 800px;
  margin: 0 auto;
  background: #fff;
  border: 1px solid #eee;
}

.loading-text {
  font-size: 1.2em;
  color: #666;
}

.flex-container {
  display: flex;
  flex-direction: column;
}

.flex-container-row {
  display: flex;
  flex-direction: row;
  justify-content: space-between;
}

.flex-row-left {
  margin-right: 40%;
}

.flex-row-right {
  margin-left: 40%;
}

@media all and (min-width: 641px) {
  .buttonfont {
    font-size: 14px;
  }
}

@media only screen and (max-width: 640px) {
  .flex-container {
    flex-direction: row;
    padding-bottom: 4px;
  }

  .flex-row {
    padding-right: 10px;
  }

  .flex-row-left {
    margin-right: 30%;
  }

  .flex-row-right {
    margin-left: 30%;
  }

  .navbar {
    height: 70px;
    padding: 10px 3px;
  }

  .DONTPrint a {
    line-height: 13px;
  }

  .mobilehide {
    display: none;
  }

  .buttonfont {
    font-size: 0.9em;
  }
}
</style>
