// mss-app-react/src/components/weeklyText/WeekTextBase.tsx
import type { TvGame } from '#/graphQl.mjs';
import { useResetAdsenseHeight } from '#/hooks/useResetAdsenseHeight.mjs';
import WeekTextTable, { type WeekTextTableHandle } from '#text/WeekTextTable.tsx';
import { forwardRef } from 'react';
import styles from './WeekTextBase.module.css';

interface WeekTextBaseProps {
  tvGames: TvGame[];
  isBowlWeek: boolean;
  isMbkPostseason: boolean;
  showPpvColumn: boolean;
  season: string;
}

const WeekTextBase = forwardRef<WeekTextTableHandle, WeekTextBaseProps>(({
  tvGames,
  isBowlWeek,
  isMbkPostseason,
  showPpvColumn,
  season
}, ref) => {
  const mainRef = useResetAdsenseHeight();

  return (
    <main ref={mainRef} className={styles.mainContainer}>
      <p id="Directions" className={`${styles.directions} DONTPrint`}>
        All start times displayed are based on your device's location. If you have trouble selecting &amp; printing games,
        please try selecting games, changing your print settings to "Print to PDF", print, then open the PDF file and
        print that.
      </p>
      
      <WeekTextTable
        ref={ref} // 👈 Forward the macro command handler hook reference down to table
        season={season}
        isBowlWeek={isBowlWeek}
        isMbkPostseason={isMbkPostseason}
        showPpvColumn={showPpvColumn}
        tvGames={tvGames}
      />
    </main>
  );
});

export default WeekTextBase;

// mss-app/src/components/weeklyText/WeekTextBase.vue
<script setup lang="ts">
import type { TvGame } from '#/graphQl.mjs';
import WeekTextTable from '#text/WeekTextTable.vue';

const props = defineProps<{
  tvGames: TvGame[];
  isBowlWeek: boolean;
  isMbkPostseason: boolean;
  showPpvColumn: boolean;
  season: string;
}>();

const { tvGames, isBowlWeek, isMbkPostseason, showPpvColumn, season } = props;
</script>

<template>
  <div id="Main" v-reset-adsense-height>
    <p id="Directions" class="DONTPrint">
      All start times displayed are based on your device's location. If you have trouble selecting &amp; printing games,
      please try selecting games, changing your print settings to "Print to PDF", print, then open the PDF file and
      print that.
    </p>
    <WeekTextTable
      :season="season"
      :is-bowl-week="isBowlWeek"
      :is-mbk-postseason="isMbkPostseason"
      :show-ppv-column="showPpvColumn"
      :tv-games="tvGames" />
  </div>
</template>

<style scoped>
#Directions {
  margin-top: 3px;
}

#Main {
  padding-top: 130px;
}

@media only screen and (max-width: 640px) {
  #Directions {
    margin-top: 6px;
  }

  #Main {
    padding-top: 100px;
  }
}
</style>
