// mss-app/src/views/HomeView.vue
<script setup lang="ts">
import { RouterLink } from 'vue-router';
import { defineAsyncComponent, nextTick, onMounted, ref } from 'vue';
import { addMetaTags } from '@/utils/base';

const title = "Matt's College Sports on TV";

addMetaTags(title);

const linksRef = ref<HTMLElement | null>(null);
const contentRef = ref<HTMLElement | null>(null);
const facebookRef = ref<HTMLElement | null>(null);

const adjustLayout = () => {
  if (linksRef.value && contentRef.value && facebookRef.value) {
    const linksHeight = linksRef.value.clientHeight;
    const windowWidth = window.innerWidth - 6;

    contentRef.value.style.height = `${linksHeight.toString()}px`;
    facebookRef.value.style.maxWidth = `${windowWidth.toString()}px`;
  }
};

onMounted(async () => {
  await nextTick();
  adjustLayout();
});

const GoogleSearch = defineAsyncComponent(() => import('@/components/shared/GoogleSearchBar.vue'));
const TwitterRetrieval = defineAsyncComponent(() => import('@/components/TwitterRetrieval.vue'));
</script>

<template>
  <div id="Main">
    <div><img id="imgtitle" alt="Matt's College Sports" src="/images/logo.jpg" /><br /></div>
    <div id="content" ref="contentRef">
      <div id="Links" ref="linksRef">
        <RouterLink to="/season/football/2025"> 2025 Football </RouterLink><br />
        <br />
        <RouterLink to="/season/football/2024"> 2024 Football </RouterLink><br />
        <RouterLink to="/season/basketball/2024-25"> 2024-25 Men's Basketball </RouterLink><br />
        <br />
        <RouterLink to="/season/football/2023"> 2023 Football </RouterLink><br />
        <RouterLink to="/season/basketball/2023-24"> 2023-24 Men's Basketball </RouterLink><br />
        <br />
        <RouterLink to="/season/football/2022"> 2022 Football </RouterLink><br />
        <RouterLink to="/season/basketball/2022-23"> 2022-23 Men's Basketball </RouterLink><br />
        <br />
        <RouterLink to="/season/football/2021"> 2021 Football </RouterLink><br />
        <RouterLink to="/season/basketball/2021-22"> 2021-22 Men's Basketball </RouterLink><br />
        <br />
        <RouterLink to="/archive"> Archived Seasons </RouterLink>
        <p>
          Check out my
          <a href="http://mattsarzsports.blogspot.com/" target="_blank">blog</a>. Discussing college sports and how
          we're watching the games.
        </p>
      </div>
      <div id="Twitter">
        <a
          class="twitter-timeline"
          href="https://twitter.com/mattsarz?ref_src=twsrc%5Etfw"
          data-height="300"
          data-tweet-limit="5"
          >Tweets by mattsarz</a
        >
        <TwitterRetrieval />
      </div>
    </div>
    <iframe
      id="Facebook"
      ref="facebookRef"
      lazy="true"
      src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Fmattsarzsports%2F&tabs&height=80&small_header=true&adapt_container_width=true&hide_cover=true&show_facepile=false&appId"
      height="80"
      style="border: none; overflow: hidden"
      scrolling="no"
      frameborder="0"
      allowfullscreen="true"
      allowtransparency="true"
      allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share" />
    <p>
      Got a question, complaint, comment or know a game not listed here?
      <a href="mailto:footballsked@gmail.com"> Send it here </a>
    </p>
    <GoogleSearch />
  </div>
</template>

<style scoped>
#imgtitle {
  max-width: 100%;
  padding-bottom: 5px;
}

#Links,
#Twitter {
  float: left;
  display: inline;
}

#Facebook {
  border: 0;
  overflow: hidden;
}

#Main {
  padding-top: 37px;
}

@media all and (min-width: 641px) {
  #Facebook {
    height: 80px;
    width: 450px;
  }

  #Links {
    width: 45%;
    min-height: 250px;
  }

  #Twitter {
    width: 55%;
  }
}

@media only screen and (max-width: 640px) {
  #Facebook {
    height: 100px;
    width: 300px;
  }

  #Links {
    width: 100%;
    min-height: 250px;
  }

  #Twitter {
    width: 100%;
  }

  #Main {
    padding-top: 48px;
  }
}
</style>

// mss-app-react/src/views/HomeView.tsx
import { useResetAdsenseHeight } from '#/hooks/useResetAdsenseHeight.mjs';
import AdsByGoogle from '#shared/AdsByGoogle';
import CopyrightLink from '#shared/CopyrightLink';
import { addMetaTags } from '#utils/metaTags';
import React, { useEffect } from 'react';
import { Link } from 'react-router-dom';
import styles from './HomeView.module.css';

const HomeView: React.FC = () => {
  const title = "Matt's College Sports on TV";
  const mainRef = useResetAdsenseHeight();

  useEffect(() => {
    addMetaTags(title);
  }, []);

  // Handle Dynamic Twitter Script Loading
  useEffect(() => {
    // 1. If the script already exists, just tell Twitter to re-parse the button
    if (window.twttr?.widgets) {
      window.twttr.widgets.load();
      return;
    }

    // 2. Otherwise, create the script tag and inject it into the document
    const script = document.createElement('script');
    script.setAttribute('src', 'https://platform.twitter.com/widgets.js');
    script.setAttribute('async', 'true');
    script.setAttribute('charset', 'utf-8');
    document.body.appendChild(script);

    // Clean up function to remove the script if the component unmounts mid-load
    return () => {
      script.remove();
    };
  }, []);

  return (
    <>
      <main ref={mainRef} className={styles.main}>
        <div>
          <img className={styles.imgtitle} src="/images/logo.webp" loading="lazy" alt="Matt's College Sports" />
          <br />
        </div>
        <div className={styles.content}>
          <div className={styles.links}>
            <Link to="/season/football/2026"> 2026 Football </Link>
            <br />
            <br />
            <Link to="/season/football/2025"> 2025 Football </Link>
            <br />
            <Link to="/season/basketball/2025-26"> 2025-26 Men's Basketball </Link>
            <br />
            <br />
            <Link to="/season/football/2024"> 2024 Football </Link>
            <br />
            <Link to="/season/basketball/2024-25"> 2024-25 Men's Basketball </Link>
            <br />
            <br />
            <Link to="/season/football/2023"> 2023 Football </Link>
            <br />
            <Link to="/season/basketball/2023-24"> 2023-24 Men's Basketball </Link>
            <br />
            <br />
            <Link to="/season/football/2022"> 2022 Football </Link>
            <br />
            <Link to="/season/basketball/2022-23"> 2022-23 Men's Basketball </Link>
            <br />
            <br />
            <Link to="/archive"> Archived Seasons </Link>
            <p>
              Check out my{' '}
              <a href="http://mattsarzsports.blogspot.com/" target="_blank" rel="noopener">
                blog
              </a>
              . Discussing college sports and how we're watching the games.
            </p>
          </div>
        </div>
        <div className={styles.twitter}>
          <a
            href="https://twitter.com/mattsarz?ref_src=twsrc%5Etfw"
            className="twitter-follow-button"
            data-show-count="true"
          >
            Follow @mattsarz
          </a>
        </div>
        <iframe
          className={styles.facebook}
          title="Link to MattSarzSports Facebook page"
          loading="lazy"
          src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Fmattsarzsports%2F&tabs&height=80&small_header=true&adapt_container_width=true&hide_cover=true&show_facepile=false&appId"
          height={80}
          style={{ border: 'none', overflow: 'hidden' }}
          allowFullScreen={true}
        />
        <br />
        <a href="https://bsky.app/profile/mattsarz.bsky.social">
          <img
            alt="Follow mattsarz on Bluesky"
            src="https://img.shields.io/badge/Bluesky-0285FF?logo=bluesky&logoColor=fff&label=Follow%20me%20on&color=0285FF"
          />
        </a>

        <p>
          Got a question, complaint, comment or know a game not listed here?{' '}
          <a href="mailto:footballsked@gmail.com"> Send it here </a>
        </p>
        <AdsByGoogle />
      </main>
      <CopyrightLink />
    </>
  );
};

export default HomeView;
