// mss-app/src/views/SeasonView.vue
<script setup lang="ts">
import { useRoute } from 'vue-router';
import { ref, watch } from 'vue';
import ConferenceList from '@/components/ConferenceList.vue';
import SeasonDates from '@/components/SeasonDates.vue';
import { useSeasonContents } from '@/composables/useSeasonContents';
import { validSportYears } from '@/constants/validSportYears';
import { addMetaTags } from '@/utils/metaTags';
import Copyright from '@/components/shared/CopyrightLink.vue';
import AdsByGoogle from '@/components/shared/AdsByGoogle.vue';

const conferenceListBase = (sport: string, year: string): string => {
  return sport === 'football' && year !== '2021s'
    ? (validSportYears.find((validSportYear) => validSportYear.season === year)?.conferenceListBase ?? '')
    : '';
};

const createTitle = (sport: string, year: string): string => {
  const capitalized = `${sport.charAt(0).toUpperCase()}${sport.slice(1)}`;
  return `${year} ${capitalized} Season`;
};

const route = useRoute();
const sport = route.params.sport as string;
const paramYear = route.params.year as string;
const year = sport === 'football' ? paramYear : `${paramYear.substring(0, 4)}${paramYear.substring(5)}`;

const title = createTitle(sport, paramYear);

addMetaTags(title);

const { result, loading, error } = useSeasonContents(year);

const conferenceList = conferenceListBase(sport, year);

const contentRef = ref<HTMLElement | null>(null);
const seasonLinksRef = ref<HTMLElement | null>(null);
const conferenceRef = ref<HTMLElement | null>(null);

const updateStyles = () => {
  if (contentRef.value && seasonLinksRef.value) {
    const contentWidth = contentRef.value.clientWidth;
    const height = seasonLinksRef.value.clientHeight;

    if (contentWidth > 640) {
      contentRef.value.style.minHeight = `${height.toString()}px`;
      if (conferenceRef.value) {
        conferenceRef.value.style.minHeight = `${height.toString()}px`;
      }
    }
  }
};

watch(result, updateStyles);
</script>

<template>
  <nav class="navbar DONTPrint">
    <div class="container">
      <div><RouterLink to="/"> Home </RouterLink><br /></div>
    </div>
  </nav>
  <div id="Main">
    <p>{{ title }}</p>
    <template v-if="error">Got a problem. Let Matt know.</template>
    <template v-if="loading">Loading...</template>
    <template v-if="result && result.seasonContents">
      <div id="content" ref="contentRef">
        <div id="SeasonLinks" ref="seasonLinksRef" class="DONTPrint">
          <SeasonDates :contents="result.seasonContents" :param-year="paramYear" :year="year" :sport="sport" />
        </div>
        <ConferenceList v-if="sport === 'football'" :conference-list="conferenceList" :year="paramYear" />
      </div>
    </template>
    <div class="inline-block">
      <p>
        <span id="Label9"> Got a question, complaint, comment or know a game not listed here? </span
        ><a id="HyperLink32" href="mailto:footballsked@gmail.com">Send it here</a>
      </p>
    </div>
    <AdsByGoogle />
    <Copyright />
  </div>
</template>

<style scoped>
#SeasonLinks,
#Conference {
  float: left;
  display: inline;
}

#SeasonLinks {
  min-height: 250px;
}

#Main {
  padding-top: 29px;
}

.inline-block {
  display: inline-block;
}

@media all and (min-width: 641px) {
  #SeasonLinks {
    width: 55%;
  }

  #Conference {
    width: 35%;
    min-height: 380px;
  }
}

@media only screen and (max-width: 640px) {
  #SeasonLinks {
    width: 100%;
  }

  .DONTPrint a {
    line-height: 13px;
  }
}
</style>

// mss-app-react/src/views/SeasonView.tsx
import { useResetAdsenseHeight, useSeasonContents } from '#hooks/index.mjs'; // Adjust hook import path as needed
import ConferenceList from '#season/ConferenceList.tsx';
import SeasonDates from '#season/SeasonDates.tsx';
import AdsByGoogle from '#shared/AdsByGoogle.tsx';
import Copyright from '#shared/CopyrightLink.tsx';
import { addMetaTags } from '#utils/metaTags.mjs';
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import styles from './SeasonView.module.css';

const SeasonView: React.FC = () => {
  const { sport = '', year: paramYear = '' } = useParams<{ sport: string; year: string }>();
  const mainRef = useResetAdsenseHeight();

  const year = sport === 'football' ? paramYear : `${paramYear.substring(0, 4)}${paramYear.substring(5)}`;

  const capitalizedSport = sport.charAt(0).toUpperCase() + sport.slice(1);
  const title = `${paramYear} ${capitalizedSport} Season`;

  // Update meta tags when title dependencies change
  useEffect(() => {
    addMetaTags(title);
  }, [title]);

  const { result, loading, error } = useSeasonContents(year);

  return (
    <>
      <nav role="navigation" className={`${styles.navbar} DONTPrint`}>
        <div className={styles.container}>
          <div className={styles.flexContainer}>
            <div>
              <Link className={styles.homelink} to="/">
                Home
              </Link>
            </div>
            <div>
              <br />
            </div>
          </div>
        </div>
      </nav>

      <main ref={mainRef}>
        <p>{title}</p>

        {/* Error Handling State */}
        {error && <>Got a problem. Let Matt know.</>}

        {/* Loading State */}
        {loading && (
          <div className={styles.loadingContainer}>
            <p className={styles.loadingText}>Loading {paramYear} season</p>
          </div>
        )}

        {/* Successful Data State */}
        {result?.seasonContents && (
          <div id="content">
            <div className={`${styles.seasonLinks} DONTPrint`}>
              <SeasonDates
                contents={result.seasonContents.seasonContents}
                paramYear={paramYear}
                sport={sport}
                hasBasketballPostseason={result.seasonContents.hasPostseason}
              />
            </div>

            {sport === 'football' && (
              <ConferenceList conferenceList={result.seasonContents.conferenceListBase ?? ''} year={paramYear} />
            )}
          </div>
        )}

        {/* Always visible bottom markup */}
        <div className={styles.inlineBlock}>
          <p>
            <span id="Label9"> Got a question, complaint, comment or know a game not listed here? </span>
            <a id="HyperLink32" href="mailto:footballsked@gmail.com">
              Send it here
            </a>
          </p>
        </div>

        <AdsByGoogle />
        <Copyright />
      </main>
    </>
  );
};

export default SeasonView;
