// mss-app/src/views/WeeklyScheduleView.vue
<script setup lang="ts">
import { addMetaTags } from '#utils/metaTags.mjs';
import { setupPrintListener } from '#utils/printListener.mts';
import { generateWeeklyTitle } from '#utils/weeklyTitle.mjs';
import WeekSchedule from '#weekly/WeekSchedule.vue';
import { useRoute } from 'vue-router';

const route = useRoute();
const { week, sport, year: paramYear } = route.params as { week: string; sport: string; year: string };

const title = generateWeeklyTitle(sport, week, paramYear, false);

addMetaTags(title);

setupPrintListener();
</script>

<template>
  <WeekSchedule :key="route.fullPath" v-reset-adsense-height :week="week" :sport="sport" :param-year="paramYear" />
</template>

// mss-app-react/src/views/WeeklyScheduleView.tsx
import { addMetaTags } from '#utils/metaTags.mjs';
import { setupPrintListener } from '#utils/printListener.mjs';
import { generateWeeklyTitle } from '#utils/weeklyTitle.mjs';
import { WebExclusivesProvider } from '#weekly/WebExclusiveContext.tsx';
import WeekSchedule from '#weekly/WeekSchedule.tsx';
import React, { useEffect } from 'react';
import { useLocation, useParams } from 'react-router-dom';

const WeeklyScheduleView: React.FC = () => {
  const {
    week = '',
    sport = '',
    year: paramYear = '',
  } = useParams<{
    week: string;
    sport: string;
    year: string;
  }>();

  const location = useLocation();

  const title = generateWeeklyTitle(sport, week, paramYear, false);

  // Sync meta tags whenever the routing dependencies change the title
  useEffect(() => {
    addMetaTags(title);
  }, [title]);

  // Bind the window print listener once when the view mounts
  useEffect(() => {
    setupPrintListener();
  }, []);

  return (
    <WebExclusivesProvider>
      <WeekSchedule
        /* Replicating :key="route.fullPath" triggers a total component unmount 
        and clean state reset on internal route alterations 
      */
        key={location.pathname}
        week={week}
        sport={sport}
        paramYear={paramYear}
      />
    </WebExclusivesProvider>
  );
};

export default WeeklyScheduleView;
