// mss-app-react/src/components/conference/ConferenceTable.tsx
import type { ConferenceGame } from '#/graphQl.mjs';
import { sanitizeHtml, formatGame, formatTime } from '#utils/index.mjs';
import { DateTime } from 'luxon';
import React, { useMemo } from 'react';
import styles from './ConferenceTable.module.css';

interface ConferenceTableProps {
  games: ConferenceGame[];
  year?: string; // Kept optional as it wasn't explicitly used in the Vue script template
}

const ConferenceTable: React.FC<ConferenceTableProps> = ({ games }) => {
  // Helper to determine the local or regional datetime source
  const getTimeSource = (timeWithOffset: string) => {
    const eastern = DateTime.fromISO(timeWithOffset).setZone('America/New_York');
    return eastern.toFormat('t') === '12:00 AM' ? eastern : DateTime.fromISO(timeWithOffset).toLocal();
  };

  // Replicating Vue's computed mapping with useMemo
  const formattedGames = useMemo(() => {
    if (!games) return [];

    return games.map((game) => {
      const timeSource = getTimeSource(game.timeWithOffset);
      return {
        ...game,
        formattedNetwork: game.network ?? '',
        formattedTime: {
          day: timeSource.toFormat('cccc'),
          date: timeSource.toFormat('LL/dd'),
          time: formatTime(game.timeWithOffset),
        },
      };
    });
  }, [games]);

  return (
    <table className={styles.noTVTable}>
      <thead>
        <tr className={styles.header}>
          <th scope="col">Game</th>
          <th scope="col">Network</th>
          <th scope="col">Time</th>
        </tr>
      </thead>
      <tbody>
        {formattedGames.map((game, index) => {
          // Destructure structural fields for simpler inline layout evaluations
          const { visitingTeam = [], homeTeam = [], location, gameTitle, formattedNetwork, formattedTime } = game;

          const hasVisitingTeams = visitingTeam.length > 0 && visitingTeam[0] !== '';
          const isStandardMatchup = visitingTeam.length === 1 && homeTeam.length === 1 && visitingTeam[0] !== '';

          return (
            <tr key={index}>
              <td className={styles.game}>
                {gameTitle && (
                  <>
                    <span className={styles.gameTitle}>{gameTitle}</span>
                    <br />
                  </>
                )}

                {/* Matchup template condition logic */}
                {!hasVisitingTeams ? null : isStandardMatchup ? (
                  <>
                    {visitingTeam[0]} {location ? 'vs.' : 'at'} {homeTeam[0]}
                    <br />
                  </>
                ) : (
                  <div dangerouslySetInnerHTML={{ __html: sanitizeHtml(formatGame(game)) }} />
                )}

                {location && <> (at {location}) </>}
              </td>

              <td className={styles.network} dangerouslySetInnerHTML={{ __html: sanitizeHtml(formattedNetwork) }} />

              <td className={styles.time}>
                {formattedTime.day}
                <br />
                {formattedTime.date}
                <br />
                {formattedTime.time}
              </td>
            </tr>
          );
        })}
      </tbody>
    </table>
  );
};

export default ConferenceTable;

// mss-app/src/components/conference/ConferenceTable.vue
<script setup lang="ts">
import type { ConferenceGame } from '@/graphQl';
import { formatGame, formatTime } from '@/utils/game';
import { DateTime } from 'luxon';
import { computed } from 'vue';

const props = defineProps<{ games: ConferenceGame[] }>();
const { games } = props;

const formattedGames = computed(() =>
  games.map((game) => {
    const easternTime = DateTime.fromISO(game.timeWithOffset).setZone('America/New_York');
    const isMidnightEastern = easternTime.toFormat('t') === '12:00 AM';
    const dayFormat = 'cccc';
    const dateFormat = 'LL/dd';
    const timeSource = isMidnightEastern ? easternTime : DateTime.fromISO(game.timeWithOffset).toLocal();

    return {
      ...game,
      formattedNetwork: game.network ?? '',
      formattedTime: {
        day: timeSource.toFormat(dayFormat),
        date: timeSource.toFormat(dateFormat),
        time: formatTime(game.timeWithOffset)
      }
    };
  })
);
</script>

<template>
  <table class="noTVTable">
    <thead>
      <tr class="header">
        <th>Game</th>
        <th>Network</th>
        <th>Time</th>
      </tr>
    </thead>
    <tbody>
      <tr v-for="(game, index) in formattedGames" :key="index">
        <td class="game">
          <template v-if="game.gameTitle">
            <span class="gameTitle">{{ game.gameTitle }}</span>
            <br />
          </template>
          <template v-if="game.visitingTeam.length === 0" />
          <template v-else-if="game.visitingTeam.length === 1 && game.homeTeam.length === 1">
            {{ game.visitingTeam[0] }} {{ game.location ? 'vs.' : 'at' }} {{ game.homeTeam[0] }}<br />
          </template>
          <template v-else>
            <div v-dompurify-html="formatGame(game)" />
          </template>
          <template v-if="game.location"> (at {{ game.location }}) </template>
        </td>
        <td v-dompurify-html="game.formattedNetwork" class="network" />
        <td class="time">
          {{ game.formattedTime.day }}<br />{{ game.formattedTime.date }}<br />{{ game.formattedTime.time }}
        </td>
      </tr>
    </tbody>
  </table>
</template>

<style scoped>
.game,
.time,
.network {
  border: medium solid Gray;
  border-width: thin;
}

.header {
  text-align: center;
}

.network {
  width: 30%;
  padding: 2px;
  text-align: center;
}

.time {
  width: 15%;
  text-align: right;
  padding: 2px;
}

.game {
  width: 55%;
  padding: 2px;
}

.noTVTable {
  background-color: #fff;
  border: 2px ridge #fff;
  border-spacing: 1px;
  border-collapse: collapse;
  width: 100%;
  max-width: 550px;
  table-layout: auto;
  /* Prevent column width changes */
}

:deep(.linkblock) {
  display: inline-block;
  padding-top: 7px;
  padding-bottom: 2px;
}

.gameTitle {
  font-weight: bold;
  font-style: italic;
}

@media only screen and (max-width: 640px) {
  .game {
    padding: 1px;
  }

  .network {
    padding: 0;
  }
}
</style>
