// mss-app-react/src/components/season/WeekLink.tsx
import type { WeekInfo } from '#/graphQl.mjs';
import React from 'react';
import { Link } from 'react-router-dom';

interface WeekLinkProps {
  content: WeekInfo;
  sport: string;
  linkText: string;
  year: string;
}

const WeekLink: React.FC<WeekLinkProps> = ({ content, sport, linkText, year }) => {
  return (
    <>
      <Link to={`/schedule/${sport}/${year}/${content.week}`}>{linkText}</Link>
      <br />
    </>
  );
};

export default WeekLink;

// mss-app/src/components/WeekLink.vue
<script lang="ts" setup>
import { RouterLink } from 'vue-router';
import type { WeekInfo } from '@/graphQl';

const props = defineProps<{
  content: WeekInfo;
  sport: string;
  linkText: string;
  year: string;
}>();
const { content, sport, linkText, year } = props;
</script>

<template>
  <RouterLink :to="`/schedule/${sport}/${year}/${content.week}`">
    {{ linkText }} </RouterLink
  ><br />
</template>
