// mss-app-react/src/components/weekly/WeeklyBase.tsx
import type { TvGame } from '#/graphQl.mjs';
import { useResetAdsenseHeight } from '#hooks/index.mjs';
import { getDateForGame } from '#utils/index.mjs';
import { WeekGamesTable } from '#weekly/index.tsx';
import React, { useMemo } from 'react';
import styles from './WeeklyBase.module.css';

interface WeeklyBaseProps {
  tvGames: TvGame[];
  isBowlWeek: boolean;
  isMbkPostseason: boolean;
  isDaily: boolean;
  showPpvColumn: boolean;
}

const WeeklyBase: React.FC<WeeklyBaseProps> = ({ tvGames, isBowlWeek, isMbkPostseason, isDaily, showPpvColumn }) => {
  const mainRef = useResetAdsenseHeight();

  const hasValidTime = (game: TvGame): game is TvGame & { timeWithOffset: string } =>
    typeof game.timeWithOffset === 'string';

  type GamesByDate = Record<string, TvGame[]>;

  // Group games dynamically into an associative map dictionary matching Vue's reducer
  const tvGamesByDate = useMemo<GamesByDate>(() => {
    if (!tvGames) return {};

    return tvGames.filter(hasValidTime).reduce<GamesByDate>((acc, game) => {
      const date = getDateForGame(game.timeWithOffset);
      if (date) {
        acc[date] ??= [];
        acc[date].push(game);
      }
      return acc;
    }, {});
  }, [tvGames]);

  // Extract keys and apply natural sorting order bounds
  const datesList = useMemo(() => {
    return Object.keys(tvGamesByDate).sort();
  }, [tvGamesByDate]);

  // Flatten Vue array class checks into a clean text conditional layout string
  const mainPaddingClass =
    isMbkPostseason || isBowlWeek ? styles.shortMainPadding : isDaily ? styles.dailyPadding : styles.mainPadding;

  return (
    <main ref={mainRef} className={mainPaddingClass}>
      <div id="WeeksBase">
        {datesList.length === 0 ? (
          <p>There are no televised games at this time</p>
        ) : (
          <>
            <p>
              <strong>All start times displayed are based on your device&apos;s location.</strong>
            </p>
            {datesList.map((weekDate) => (
              <div key={weekDate}>
                <WeekGamesTable
                  weekDate={weekDate}
                  isBowlWeek={isBowlWeek}
                  isMbkPostseason={isMbkPostseason}
                  showPpvColumn={showPpvColumn}
                  tvGamesForDate={tvGamesByDate[weekDate]}
                />
              </div>
            ))}
          </>
        )}
      </div>
    </main>
  );
};

export default WeeklyBase;

// mss-app/src/components/WeeklyBase.vue
<script setup lang="ts">
import type { TvGame } from '@/graphQl';
import { adjustNavBar } from '@/utils/dom';
import { DateTime } from 'luxon';
import { computed, onMounted } from 'vue';
import WeekGamesTable from '@/components/weekly/WeekGamesTable.vue';

const props = defineProps<{
  tvGames: TvGame[];
  isBowlWeek: boolean;
  isMbkPostseason: boolean;
  showPpvColumn: boolean;
  season: string;
}>();

const { tvGames, isBowlWeek, isMbkPostseason, showPpvColumn, season } = props;

const datesList = computed(() => {
  const dates = new Set<string>();
  tvGames.forEach((value) => {
    if (value.timeWithOffset) {
      const date = DateTime.fromISO(value.timeWithOffset).toLocal().toISODate();
      if (date) {
        dates.add(date);
      }
    }
  });
  return Array.from(dates);
});

const tvGamesByDate = computed(() => {
  const gamesByDate: Record<string, TvGame[]> = {};
  datesList.value.forEach((date) => {
    gamesByDate[date] = tvGames.filter(
      (game) => game.timeWithOffset && DateTime.fromISO(game.timeWithOffset).toLocal().toISODate() === date
    );
  });
  return gamesByDate;
});

onMounted(() => {
  adjustNavBar();
});
</script>

<template v-if="datesList.length">
  <div id="Main">
    <div id="WeeksBase">
      <template v-if="tvGames.length === 0">
        <p>There are no televised games at this time</p>
      </template>
      <template v-else>
        <p>
          <b>All start times displayed are based on your device's location.</b>
        </p>
        <div v-for="(weekDate, index) in datesList" :key="index">
          <WeekGamesTable
            :season="season"
            :week-date="weekDate"
            :is-bowl-week="isBowlWeek"
            :is-mbk-postseason="isMbkPostseason"
            :show-ppv-column="showPpvColumn"
            :tv-games-for-date="tvGamesByDate[weekDate]" />
        </div>
      </template>
    </div>
  </div>
</template>
