// mss-app-react/src/App.tsx
import { useAppUtils } from '#/hooks/useAppUtils.mjs';
import { routes } from '#/router';
import { checkVersion } from '#/utils/versionCheck.mjs';
import React, { useEffect, useRef, useState } from 'react';
import { BrowserRouter, Navigate, Route, Routes } from 'react-router-dom';
import '#/App.css';

const App: React.FC = () => {
  const [needsUpdate, setNeedsUpdate] = useState(false);
  const { isOnline } = useAppUtils();
  const checkIntervalRef = useRef<ReturnType<typeof setInterval> | undefined>(undefined);

  useEffect(() => {
    // Check for updates every 5 minutes
    checkIntervalRef.current = setInterval(async () => {
      const hasUpdate = await checkVersion();
      setNeedsUpdate(hasUpdate);
    }, 300000);

    return () => {
      if (checkIntervalRef.current) {
        clearInterval(checkIntervalRef.current);
      }
    };
  }, []);

  const handleReload = () => window.location.reload();

  return (
    <BrowserRouter>
      <div className="maincontainer">
        {needsUpdate && (
          <div className="update-banner">
            A new version is available.
            <button onClick={handleReload}>Refresh</button>
          </div>
        )}
        {!isOnline && <div className="offline-banner">You are currently offline</div>}
        <Routes>
          {routes.map((route) => (
            <Route key={route.path} path={route.path} element={route.element} />
          ))}
          {/* Catch-all route for 404s - redirect to home */}
          <Route path="*" element={<Navigate to="/" replace />} />
        </Routes>
      </div>
    </BrowserRouter>
  );
};

export default App;

// mss-app/src/App.vue
<script setup lang="ts">
import { useAppUtils } from '#composables/useAppUtils.mjs';
import { checkVersion } from '#utils/versionCheck.mjs';
import { onMounted, onUnmounted, ref } from 'vue';
import { RouterView } from 'vue-router';

const { isOnline } = useAppUtils();

const needsUpdate = ref(false);

const reload = () => window.location.reload();

onMounted(() => {
  const checkInterval = setInterval(async () => {
    needsUpdate.value = await checkVersion();
  }, 300000); // Check every 5 minutes

  onUnmounted(() => clearInterval(checkInterval));
});
</script>

<template>
  <div v-reset-adsense-height class="maincontainer">
    <div v-if="needsUpdate" class="update-banner">
      A new version is available.
      <button @click="reload()">Refresh</button>
    </div>
    <div v-if="!isOnline" class="offline-banner">You are currently offline</div>
    <RouterView />
  </div>
</template>

<style scoped>
.update-banner {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  background: #4caf50;
  color: white;
  padding: 1rem;
  text-align: center;
  z-index: 99999;
}
</style>
