// mss-app-react/src/views/DailyScheduleView.tsx
import { useResetAdsenseHeight } from '#/hooks/useResetAdsenseHeight.mjs';
import { useWebExclusivesContext } from '#/hooks/useWebExclusivesContext.mjs';
import { useDailyTvGames } from '#hooks/useDailyTvGames.mjs';
import Copyright from '#shared/CopyrightLink.tsx';
import { addMetaTags } from '#utils/metaTags.mjs';
import { setupPrintListener } from '#utils/printListener.mjs';
import { WebExclusivesProvider } from '#weekly/WebExclusiveContext.tsx';
import WeeklyBase from '#weekly/WeeklyBase.tsx';
import { DateTime } from 'luxon';
import React, { Suspense, useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import styles from './DailyScheduleView.module.css';

// Lazy-Loaded Core Sub-Components
const BackToTop = React.lazy(() => import('#shared/BackToTop.tsx'));
const AdsByGoogle = React.lazy(() => import('#shared/AdsByGoogle.tsx'));

const DailyTvGamesInner: React.FC = () => {
  const mainRef = useResetAdsenseHeight();
  // Pulling parameters via React Router DOM hook
  const { sport } = useParams<{ sport: string }>() as { sport: string };

  const {
    result: dailyTvGameResult,
    loading: dailyTvGameLoading,
    error: dailyTvGameError,
    season,
    startDate,
  } = useDailyTvGames(sport);

  // Grab values out of the surrounding context pool wrapper
  const { toggleWebExclusives, buttonText } = useWebExclusivesContext();

  useEffect(() => {
    const title = `Daily TV Games for ${DateTime.now().toFormat('LLLL dd, yyyy')}`;
    addMetaTags(title);

    setupPrintListener();
  }, []);

  return (
    <main ref={mainRef}>
      {/* Loading Template View Tree */}
      {dailyTvGameLoading && (
        <div className={styles.loadingContainer}>
          <p className={styles.loadingText}>
            Loading {sport} for {startDate}
          </p>
        </div>
      )}

      {/* Error Template View Tree */}
      {dailyTvGameError && (
        <div className={styles.errorContainer}>
          <p>Sorry. Got a bit of a problem. Let Matt know.</p>
        </div>
      )}

      {/* Main Content Layout Block */}
      {dailyTvGameResult && (
        <>
          <nav role="navigation" className={`${styles.navbar} DONTPrint`}>
            <div className={styles.container}>
              <div className={styles.flexContainer}>
                <div className={styles.flexRow}>
                  <Link to="/">Home</Link>
                </div>
                {season && (
                  <div className={styles.flexRow}>
                    <Link to={`/season/${sport}/${season}`}>Season Home</Link>
                  </div>
                )}
              </div>

              <div className={styles.flexContainer}>
                {dailyTvGameResult.dailyTvGames?.flexScheduleLink && (
                  <div className={styles.flexRow}>
                    <Link to={`/tv-windows/${season}`} target="_blank" rel="noopener">
                      Available TV Windows
                    </Link>
                  </div>
                )}
                <div className={styles.flexRow}>
                  <Link to={`/schedule/${sport}/daily/text`}>Customizable Text-Only Page</Link>
                </div>
                <br />
              </div>

              <div className={styles.filters}>
                <button
                  id="btnWebGames"
                  type="button"
                  className={`${styles.show_hideWeb} ${styles.buttonfont}`}
                  onClick={toggleWebExclusives}
                >
                  {buttonText}
                </button>
              </div>
            </div>
          </nav>

          <WeeklyBase
            tvGames={dailyTvGameResult.dailyTvGames!.tvGames}
            isBowlWeek={false}
            isMbkPostseason={false}
            isDaily={true}
            showPpvColumn={dailyTvGameResult.dailyTvGames!.showPPVColumn}
          />

          <Suspense fallback={null}>
            <BackToTop />
            <AdsByGoogle />
          </Suspense>

          <Copyright />
        </>
      )}
    </main>
  );
};

// Main Export wrapping the Inner Component in the WebExclusives Context Provider
const DailyTvGamesView: React.FC = () => {
  return (
    <WebExclusivesProvider>
      <DailyTvGamesInner />
    </WebExclusivesProvider>
  );
};

export default DailyTvGamesView;

// mss-app/src/views/DailyScheduleView.vue
<script setup lang="ts">
import { useDailyTvGames } from '#composables/useDailyTvGames.mjs';
import { useWebExclusives } from '#composables/useWebExclusives.mjs';
import Copyright from '#shared/CopyrightLink.vue';
import { addMetaTags } from '#utils/metaTags.mjs';
import { setupPrintListener } from '#utils/printListener.mts';
import WeeklyBase from '#weekly/WeeklyBase.vue';
import { DateTime } from 'luxon';
import { defineAsyncComponent } from 'vue';
import { useRoute } from 'vue-router';

const AdsByGoogle = defineAsyncComponent(() => import('#shared/AdsByGoogle.vue'));
const BackToTop = defineAsyncComponent(() => import('#shared/BackToTop.vue'));

const route = useRoute();
const { sport } = route.params as { sport: string };

const title = `Daily TV Games for ${DateTime.now().toFormat('LLLL dd, yyyy')}`;

const { buttonText, toggleWebExclusives } = useWebExclusives();

addMetaTags(title);

const {
  result: dailyTvGameResult,
  loading: dailyTvGameLoading,
  error: dailyTvGameError,
  season,
  startDate
} = useDailyTvGames(sport);

setupPrintListener();
</script>

<template>
  <div v-reset-adsense-height>
    <template v-if="dailyTvGameLoading">
      <div class="loading-container">
        <p class="loading-text">Loading {{ sport }} for {{ startDate }}</p>
      </div>
    </template>
    <template v-if="dailyTvGameError">
      <div class="error-container">
        <p>Sorry. Got a bit of a problem. Let Matt know.</p>
      </div>
    </template>
    <template v-if="dailyTvGameResult">
      <nav role="navigation" class="navbar DONTPrint">
        <div class="container">
          <div class="flex-container">
            <div class="flex-row">
              <RouterLink to="/">Home</RouterLink>
            </div>
            <div v-if="season" class="flex-row">
              <RouterLink :to="`/season/${sport}/${season}`">Season Home</RouterLink>
            </div>
          </div>
          <div class="flex-container">
            <div v-if="dailyTvGameResult.dailyTvGames.flexScheduleLink" class="flex-row">
              <RouterLink :to="`/tv-windows/${season}`" target="_blank" rel="noopener"
                >Available TV Windows
              </RouterLink>
            </div>
            <div class="flex-row">
              <RouterLink :to="`/schedule/${sport}/daily/text`">Customizable Text-Only Page </RouterLink>
            </div>
            <br />
          </div>
          <div v-if="dailyTvGameResult" class="filters">
            <button id="btnWebGames" class="show_hideWeb buttonfont" @click="toggleWebExclusives">
              {{ buttonText }}
            </button>
          </div>
        </div>
      </nav>
      <WeeklyBase
        :tv-games="dailyTvGameResult.dailyTvGames.tvGames"
        :is-bowl-week="false"
        :is-mbk-postseason="false"
        :is-daily="true"
        :show-ppv-column="dailyTvGameResult.dailyTvGames.showPPVColumn" />
      <BackToTop />
      <AdsByGoogle />
      <Copyright />
    </template>
  </div>
</template>

<style scoped>
.show_hideWeb {
  display: inline-block;
}

:deep(.imgBorder) {
  border: 0;
}

:deep(img) {
  aspect-ratio: 66 / 50;
}

.filters {
  margin: 0;
}

.navbar {
  position: fixed;
  top: 0;
  left: 0;
  z-index: 9999;
  width: 100%;
  background-color: white;
  padding: 2px 0;
  box-shadow: 0 1px 1px rgba(0, 0, 0, 0.1);
  min-height: 70px;
  display: block;
  align-items: center;
}

.container {
  height: 100%;
  max-width: 800px;
  margin: 0 auto;
}

.loading-container,
.error-container {
  min-height: 200px;
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  max-width: 800px;
  margin: 0 auto;
  background: #fff;
  border: 1px solid #eee;
}

.loading-text {
  font-size: 1.2em;
  color: #666;
}

.flex-container {
  display: flex;
  flex-direction: column;
}

@media all and (min-width: 641px) {
  .filters {
    margin-top: 10px;
  }

  .buttonfont {
    font-size: 14px;
  }
}

@media only screen and (max-width: 640px) {
  .flex-container {
    flex-direction: row;
    padding-bottom: 4px;
  }

  .flex-row {
    padding-right: 10px;
  }

  .blockspan {
    display: block;
    padding-bottom: 3px;
  }

  .filters {
    margin-top: 5px;
  }

  .buttonfont {
    font-size: 0.9em;
  }

  .navbar {
    height: 58px;
    padding: 10px 3px;
  }

  :deep(img) {
    aspect-ratio: 43 / 33;
  }
}
</style>
