// mss-app-react/src/views/DailyTextScheduleView.tsx
import { useDailyTvTextGames } from '#hooks/index.mjs';
import { BackToTop, CopyrightLink } from '#shared/index.mjs';
import { formatDateLong } from '#utils/dateFormatting.mjs';
import { checkAllTextRows, clearAllSelectedTextRows } from '#utils/domText.mjs';
import { addMetaTags } from '#utils/metaTags';
import { setupPrintListener } from '#utils/printListener.mjs';
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import AdsByGoogle from '../components/shared/AdsByGoogle.tsx';
import WeekTextBase from '../components/weeklyText/WeekTextBase.tsx';

const DailyTextScheduleView: React.FC = () => {
  const { sport = '' } = useParams<'sport'>();
  const {
    dailyTvGameResult: result,
    dailyTvGameLoading: loading,
    dailyTvGameError: error,
    season,
    paramYear,
    startDate
  } = useDailyTvTextGames(sport);

  const title = `Daily TV Games for ${formatDateLong(new Date())}`;

  useEffect(() => {
    addMetaTags(title);
    setupPrintListener();
  }, []);

  if (loading) {
    return (
      <div style={{ minHeight: '200px', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
        <p style={{ fontSize: '1.2em', color: '#666' }}>Loading {sport} for {startDate}</p>
      </div>
    );
  }

  if (error) {
    return (
      <div style={{ minHeight: '200px', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
        <p>Sorry. Got a bit of a problem. Let Matt know.</p>
      </div>
    );
  }

  const games = result?.dailyTvGames?.tvGames ?? [];

  return (
    <div>
      <nav
        role="navigation"
        className="navbar DONTPrint"
        style={{
          position: 'fixed',
          top: 0,
          left: 0,
          right: 0,
          zIndex: 9999,
          width: '100%',
          backgroundColor: 'white',
          padding: '2px 0',
          boxShadow: '0 1px 1px rgba(0, 0, 0, 0.1)',
          height: '119.5px',
          display: 'block'
        }}
      >
        <div style={{ maxWidth: '800px', margin: '0 auto', height: '100%' }}>
          <div style={{ display: 'flex', gap: '20px', padding: '10px' }}>
            <Link to="/" style={{ textDecoration: 'none', color: '#2196f3' }}>Home</Link>
            <Link to={`/season/${sport}/${season}`} style={{ textDecoration: 'none', color: '#2196f3' }}>Season Home</Link>
            <Link to={`/schedule/${sport}/daily`} className="DONTPrint" style={{ textDecoration: 'none', color: '#2196f3' }}>Daily Schedule</Link>
          </div>
          <div style={{ padding: '5px 10px' }} className="DONTPrint">
            <button
              id="ClearAll"
              className="inputpad buttonfont"
              onClick={clearAllSelectedTextRows}
              style={{
                padding: '10px 15px',
                marginRight: '10px',
                backgroundColor: '#f44336',
                color: 'white',
                border: 'none',
                borderRadius: '4px',
                cursor: 'pointer'
              }}
            >
              Clear All Games
            </button>
            <button
              id="CheckAll"
              className="inputpad buttonfont"
              onClick={checkAllTextRows}
              style={{
                padding: '10px 15px',
                backgroundColor: '#4CAF50',
                color: 'white',
                border: 'none',
                borderRadius: '4px',
                cursor: 'pointer'
              }}
            >
              Check All Games
            </button>
          </div>
        </div>
      </nav>
      <main style={{ paddingTop: '130px' }}>
        <WeekTextBase games={games} sport={sport} />
      </main>
      <BackToTop />
      <AdsByGoogle />
      <CopyrightLink />
    </div>
  );
};

export default DailyTextScheduleView;

// mss-app/src/views/DailyTextScheduleView.vue
<script setup lang="ts">
import { useDailyTvTextGames } from '#composables/useDailyTvTextGames.mjs';
import AdsByGoogle from '#shared/AdsByGoogle.vue';
import BackToTop from '#shared/BackToTop.vue';
import Copyright from '#shared/CopyrightLink.vue';
import WeekTextBase from '#text/WeekTextBase.vue';
import { checkAllTextRows, clearAllSelectedTextRows } from '#utils/domText.mjs';
import { addMetaTags } from '#utils/metaTags.mjs';
import { setupPrintListener } from '#utils/printListener.mts';
import { DateTime } from 'luxon';

const title = `Daily TV Games for ${DateTime.now().toFormat('LLLL dd, yyyy')}`;

addMetaTags(title);

const { dailyTvGameResult, dailyTvGameLoading, dailyTvGameError, season, paramYear, sport, startDate } =
  useDailyTvTextGames();

setupPrintListener();
</script>

<template>
  <div v-reset-adsense-height>
    <template v-if="dailyTvGameLoading">
      <div class="loading-container">
        <p class="loading-text">Loading {{ sport }} for {{ startDate }}</p>
      </div>
    </template>
    <template v-if="dailyTvGameError">
      <div class="error-container">
        <p>Sorry. Got a bit of a problem. Let Matt know.</p>
      </div>
    </template>
    <template v-if="dailyTvGameResult">
      <nav role="navigation" class="navbar DONTPrint">
        <div class="container">
          <div class="flex-container">
            <div class="flex-row">
              <RouterLink to="/">Home</RouterLink>
            </div>
            <div class="flex-row">
              <RouterLink :to="`/season/${sport}/${season}`">Season Home </RouterLink>
            </div>
            <div class="flex-row">
              <RouterLink class="DONTPrint" :to="`/schedule/${sport}/daily`"> Daily Schedule </RouterLink>
            </div>
          </div>
          <br />
          <p id="TextNav" class="pad DONTPrint">
            <button id="ClearAll" class="inputpad buttonfont" @click="clearAllSelectedTextRows">Clear All Games</button>

            <button id="CheckAll" class="inputpad buttonfont" @click="checkAllTextRows">Check All Games</button>
          </p>
        </div>
      </nav>
      <WeekTextBase
        :season="paramYear"
        :tv-games="dailyTvGameResult.dailyTvGames.tvGames"
        :is-bowl-week="false"
        :is-mbk-postseason="false"
        :show-ppv-column="dailyTvGameResult.dailyTvGames.showPPVColumn" />
      <BackToTop />
      <AdsByGoogle />
      <Copyright />
    </template>
  </div>
</template>

<style scoped>
.inputpad {
  padding-left: 10px;
  margin-right: 3px;
}

#TextNav {
  margin: 0;
}

.navbar {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  z-index: 9999;
  width: 100%;
  background-color: white;
  padding: 2px 0;
  box-shadow: 0 1px 1px rgba(0, 0, 0, 0.1);
  align-items: center;
  height: 119.5px;
  display: block;
}

.pad {
  padding: 5px 0;
}

.container {
  height: 100%;
  max-width: 800px;
  margin: 0 auto;
}

.loading-container,
.error-container {
  min-height: 200px;
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  max-width: 800px;
  margin: 0 auto;
  background: #fff;
  border: 1px solid #eee;
}

.loading-text {
  font-size: 1.2em;
  color: #666;
}

@media all and (min-width: 641px) {
  .buttonfont {
    font-size: 14px;
  }
}

@media only screen and (max-width: 640px) {
  .navbar {
    height: 60px;
    padding: 10px 3px;
  }

  .DONTPrint a {
    line-height: 13px;
  }

  .mobilehide {
    display: none;
  }

  .buttonfont {
    font-size: 0.9em;
  }
}
</style>
