// mss-app-react/src/views/TvWindowsView.tsx
import { useResetAdsenseHeight, useSeasonData } from '#hooks/index.mjs';
import AdsByGoogle from '#shared/AdsByGoogle';
import CopyrightLink from '#shared/CopyrightLink';
import { addMetaTags } from '#utils/metaTags';
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import styles from './TvWindowsView.module.css';

const TvWindowsView: React.FC = () => {
  const { year = '' } = useParams<'year'>();
  const { result, loading, error } = useSeasonData(year);
  const mainRef = useResetAdsenseHeight();

  useEffect(() => {
    // Vue uses "Football TV Windows for {year}"
    addMetaTags(`Football TV Windows for ${year}`);
  }, [year]);

  if (loading) {
    return (
      <div className={styles['loading-container']}>
        <p className={styles['loading-text']}>TV Windows Loading...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className={styles['error-container']}>
        <p>Sorry. Got a bit of a problem. Let Matt know.</p>
      </div>
    );
  }

  // Fallback check matching Vue's v-if="result" implicit expectation
  if (!result || !result.seasonData) return null;

  const FLEXLINKSETUP = '/pubhtml?widget=true&amp;headers=false';
  const iframeSrc = `${result.seasonData.flexScheduleLink}${FLEXLINKSETUP}`;

  return (
    <>
      {/* 1. Navigation Header Parity */}
      <nav role="navigation" className={`${styles.navbar} DONTPrint`}>
        <div className={styles.container}>
          <div className={styles['flex-container']}>
            <div>
              <Link to="/">Home</Link>
            </div>
            <div>
              <br />
            </div>
            <div>
              <Link to={`/season/football/${year}`}>Season Home</Link>
            </div>
          </div>
        </div>
      </nav>

      {/* 2. Main content container */}
      {/* Note: If v-reset-adsense-height is a custom directive, apply its logic via a ref hook here */}
      <main ref={mainRef}>
        <iframe title={`Football TV Windows for ${year} season`} className={styles.tvFrame} src={iframeSrc} />

        {/* 3. AdsByGoogle placed exactly under the iframe */}
        <AdsByGoogle />
      </main>

      {/* 4. Copyright placed outside main, matching the Vue tree hierarchy */}
      <CopyrightLink />
    </>
  );
};

export default TvWindowsView;

// mss-app/src/views/TvWindowsView.vue
<script setup lang="ts">
import { useSeasonData } from '#/composables/useSeasonData.mjs';
import Copyright from '#shared/CopyrightLink.vue';
import { addMetaTags } from '#utils/metaTags.mjs';
import { defineAsyncComponent } from 'vue';
import { useRoute } from 'vue-router';

const AdsByGoogle = defineAsyncComponent(() => import('#shared/AdsByGoogle.vue'));

const route = useRoute();
const { year } = route.params as { year: string };

const title = `Football TV Windows for ${year}`;

const FLEXLINKSETUP = '/pubhtml?widget=true&amp;headers=false';

addMetaTags(title);

const { result, loading, error } = useSeasonData(year);
</script>

<template>
  <template v-if="result">
    <nav role="navigation" class="navbar DONTPrint">
      <div class="container">
        <div class="flex-container">
          <div>
            <RouterLink to="/">Home</RouterLink>
          </div>
          <div><br /></div>
          <div>
            <RouterLink :to="`/season/football/${year}`">Season Home</RouterLink>
          </div>
        </div>
      </div>
    </nav>
    <main v-reset-adsense-height>
      <iframe
        :title="`Football TV Windows for ${year} season`"
        class="tvFrame"
        :src="`${result.seasonData.flexScheduleLink}${FLEXLINKSETUP}`" />
      <AdsByGoogle />
    </main>
    <Copyright />
  </template>
  <template v-if="loading">
    <div class="loading-container">
      <p class="loading-text">TV Windows Loading...</p>
    </div>
  </template>
  <template v-if="error">
    <div class="error-container">
      <p>Sorry. Got a bit of a problem. Let Matt know.</p>
    </div>
  </template>
</template>

<style scoped>
.navbar {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  z-index: 9999;
  width: 100%;
  background-color: white;
  padding: 2px 0;
  box-shadow: 0 1px 1px rgba(0, 0, 0, 0.1);
  align-items: center;
  height: 55px;
  display: block;
}

.tvFrame {
  height: 450px;
  width: 100%;
  margin-top: 60px;
}

.container {
  height: 100%;
  max-width: 800px;
  margin: 0 auto;
}

.flex-container {
  display: flex;
  flex-direction: column;
}

@media only screen and (max-width: 640px) {
  .tvFrame {
    width: 97%;
  }

  .navbar {
    height: 45px;
  }
}
</style>
