// mss-app-react/src/components/shared/BackToTopButton.tsx
import React, { useState, useEffect } from 'react';

const BackToTopButton: React.FC = () => {
  const [showButton, setShowButton] = useState(false);

  const handleScroll = () => {
    setShowButton(window.scrollY > 200);
  };

  const scrollToTop = (e: React.MouseEvent<HTMLAnchorElement>) => {
    e.preventDefault();
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  useEffect(() => {
    window.addEventListener('scroll', handleScroll);
    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, []);

  return (
    <p>
      <a
        id="backToTopBtn"
        href="#"
        onClick={scrollToTop}
        style={{
          display: showButton ? 'block' : 'none',
          position: 'fixed',
          bottom: '20px',
          right: '20px',
          opacity: showButton ? 1 : 0,
          transition: 'opacity 0.3s ease-in-out',
          cursor: 'pointer',
          zIndex: 9999
        }}
      >
        Back to top
      </a>
    </p>
  );
};

export default BackToTopButton;

// mss-app/src/components/shared/BackToTopButton.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';

const showButton = ref(false);

const handleScroll = () => {
  showButton.value = window.scrollY > 200;
};

const scrollToTop = () => {
  window.scrollTo({ top: 0, behavior: 'smooth' });
};

onMounted(() => {
  window.addEventListener('scroll', handleScroll);
});

onUnmounted(() => {
  window.removeEventListener('scroll', handleScroll);
});
</script>

<template>
  <p>
    <a
      id="backToTopBtn"
      href="#"
      :class="{ show: showButton }"
      @click.prevent="scrollToTop"
    >Back to top</a>
  </p>
</template>

<style scoped>
#backToTopBtn {
  display: none;
  position: fixed;
  bottom: 20px;
  right: 20px;
  opacity: 0;
  transition: opacity 0.3s ease-in-out;
}

#backToTopBtn.show {
  display: block;
  opacity: 1;
}
</style>
