// mss-app-react/src/components/weekly/WeekSchedule.tsx
import { useCurrentTimeET } from '#hooks/useCurrentTimeET.mjs';
import { useWeekSchedule } from '#hooks/useWeekSchedule.mjs';
import { useWeekScheduleNav } from '#hooks/useWeekScheduleNav.mjs';
import NoTvGames from '#noTv/NoTvGames.tsx';
import AdsByGoogle from '#shared/AdsByGoogle.tsx';
import BackToTop from '#shared/BackToTop.tsx';
import Copyright from '#shared/CopyrightLink.tsx';
import WeeklyBase from '#weekly/WeeklyBase.tsx';
import { DateTime } from 'luxon';
import React, { useMemo } from 'react';
import { Link } from 'react-router-dom';
import { useWebExclusivesContext } from '#weekly/WebExclusiveContext.tsx';
import styles from './WeekSchedule.module.css';

interface WeekScheduleProps {
  week: string;
  sport: string;
  paramYear: string;
}

const WeekSchedule: React.FC<WeekScheduleProps> = ({ week, sport, paramYear }) => {
  // Replicating computed year string formatting logic
  const year = useMemo(() => {
    return sport === 'football' ? paramYear : `${paramYear.slice(0, 4)}${paramYear.slice(5)}`;
  }, [sport, paramYear]);

  const { toggleWebExclusives, buttonText } = useWebExclusivesContext();
  const weekInt = useMemo(() => parseInt(week), [week]);

  const {
    seasonContentsResult,
    seasonContentsLoading,
    seasonContentsError,
    nextWeek,
    previousWeek,
    isBowlWeek,
    isMbkPostseason,
    isWeekOne,
    isNextWeekMbkPostseason,
    isNextWeekBowlWeek,
  } = useWeekScheduleNav(sport, year, weekInt);

  const { currentTimeISO } = useCurrentTimeET();

  // Replicating computed logic checking if games run today
  const gamesToday = useMemo(() => {
    const nowIso = currentTimeISO;
    if (!nowIso || !seasonContentsResult?.seasonContents?.seasonContents) return false;

    return seasonContentsResult.seasonContents.seasonContents.some(
      (content: { week: number; startDate: string; endDate: string }) => {
        if (content.week !== weekInt) return false;
        const startIso = DateTime.fromISO(content.startDate).toUTC().toISO();
        const endIso = DateTime.fromISO(content.endDate).toUTC().toISO();
        if (!startIso || !endIso) return false;
        return startIso <= nowIso && endIso >= nowIso;
      }
    );
  }, [currentTimeISO, seasonContentsResult, weekInt]);

  // Replicating computed navbar dynamic class lookup
  const navbarClass = useMemo(() => {
    if (isMbkPostseason) return styles.mbkHeight;
    if (isBowlWeek) return styles.bowlHeight;
    if (gamesToday) return styles.navbarPadHeight;
    return styles.navbarHeight;
  }, [isMbkPostseason, isBowlWeek, gamesToday]);

  const { tvGameResult, tvGameLoading, tvGameError } = useWeekSchedule(sport, year, weekInt);

  // --- Unified Status Templates ---

  if (seasonContentsLoading || tvGameLoading) {
    return (
      <div className={styles.loadingContainer}>
        <p className={styles.loadingText}>
          Loading Week {week} for {paramYear}
        </p>
      </div>
    );
  }

  if (seasonContentsError || tvGameError) {
    return (
      <div className={styles.errorContainer}>
        <p>Sorry. Got a bit of a problem. Let Matt know.</p>
      </div>
    );
  }

  return (
    <div>
      {/* Navigation Layout - Displays when data payloads resolve successfully */}
      {seasonContentsResult && tvGameResult && (
        <nav role="navigation" className={`${styles.navbar} ${styles.DONTPrint} ${navbarClass}`}>
          <div className={styles.container}>
            <div className={styles.flexContainer}>
              <div className={styles.flexRow}>
                <Link to="/">Home</Link>
              </div>
              <div className={styles.flexRow}>
                <Link to={`/season/${sport}/${paramYear}`}>Season Home</Link>
              </div>
              {gamesToday && (
                <div className={styles.flexRow}>
                  <Link to={`/schedule/${sport}/daily`}>Today's Schedule </Link>
                </div>
              )}
            </div>

            <div className={styles.flexContainer}>
              {seasonContentsResult.seasonContents?.flexScheduleLink && (
                <div className={styles.flexRow}>
                  <Link to={`/tv-windows/${paramYear}`} target="_blank" rel="noopener">
                    Available TV Windows
                  </Link>
                </div>
              )}
              <div className={styles.flexRow}>
                <Link to={`/schedule/${sport}/${paramYear}/${week}/text`}>Customizable Text-Only Page</Link>
              </div>
            </div>

            {!isMbkPostseason && !isBowlWeek && (
              <div className={`${styles.flexContainerRow} ${styles.pad}`}>
                {isWeekOne ? (
                  <div className={styles.flexRowLeft}>
                    <Link to={`/schedule/${sport}/${paramYear}/${nextWeek}`}>Next Week</Link>
                  </div>
                ) : (
                  <>
                    <div className={styles.flexRowLeft}>
                      <Link to={`/schedule/${sport}/${paramYear}/${previousWeek}`}>Previous Week</Link>
                    </div>
                    {!isNextWeekMbkPostseason && !isNextWeekBowlWeek && (
                      <div className={styles.flexRowRight}>
                        <Link to={`/schedule/${sport}/${paramYear}/${nextWeek}`}>Next Week </Link>
                      </div>
                    )}
                  </>
                )}
                <br className={styles.mobilehide} />
              </div>
            )}
            <br />

            {tvGameResult && (
              <div className={styles.filters}>
                {!isBowlWeek && !isMbkPostseason && (
                  <button
                    id="btnWebGames"
                    type="button"
                    className={`${styles.show_hideWeb} ${styles.buttonFont}`}
                    onClick={toggleWebExclusives}
                  >
                    {buttonText}
                  </button>
                )}
              </div>
            )}
          </div>
        </nav>
      )}

      {/* Main Schedule Content Output Trees */}
      {tvGameResult && (
        <>
          <WeeklyBase
            tvGames={tvGameResult.tvGames!.tvGames}
            isBowlWeek={isBowlWeek}
            isMbkPostseason={isMbkPostseason}
            isDaily={false}
            showPpvColumn={tvGameResult.tvGames!.showPPVColumn}
          />

          {!isBowlWeek && tvGameResult.tvGames!.hasNoTVGames && <NoTvGames year={year} week={week} />}

          <BackToTop />
          <AdsByGoogle />
          <Copyright />
        </>
      )}
    </div>
  );
};

export default WeekSchedule;

// mss-app/src/components/weekly/WeekSchedule.vue
<script setup lang="ts">
import { useWebExclusives } from '#composables/useWebExclusives.mjs';
import { useWeekSchedule } from '#composables/useWeekSchedule.mjs';
import { useWeekScheduleNav } from '#composables/useWeekScheduleNav.mjs';
import NoTvGames from '#noTv/NoTvGames.vue';
import AdsByGoogle from '#shared/AdsByGoogle.vue';
import BackToTop from '#shared/BackToTop.vue';
import Copyright from '#shared/CopyrightLink.vue';
import WeeklyBase from '#weekly/WeeklyBase.vue';
import { DateTime } from 'luxon';
import { computed } from 'vue';

const props = defineProps<{ week: string; sport: string; paramYear: string }>();
const { week, sport, paramYear } = props;

const year = computed(() =>
  sport === 'football' ? paramYear : `${paramYear.substring(0, 4)}${paramYear.substring(5)}`
);

const { buttonText, toggleWebExclusives } = useWebExclusives();

const weekInt = computed(() => parseInt(week));

const {
  seasonContentsResult,
  seasonContentsLoading,
  seasonContentsError,
  nextWeek,
  previousWeek,
  isBowlWeek,
  isMbkPostseason,
  isWeekOne,
  isNextWeekMbkPostseason,
  isNextWeekBowlWeek
} = useWeekScheduleNav(sport, year.value, weekInt.value);

const gamesToday = computed(() => {
  const nowInET = DateTime.now().setZone('America/New_York');
  return seasonContentsResult.value?.seasonContents.seasonContents
    .filter((content: { week: number }) => content.week === weekInt.value)
    .some((content: { startDate: string; endDate: string }) => {
      const startIso = DateTime.fromISO(content.startDate).toUTC().toISO();
      const endIso = DateTime.fromISO(content.endDate).toUTC().toISO();
      const nowIso = nowInET.toISO({ includeOffset: false });
      if (!startIso || !endIso || !nowIso) return false;
      return startIso <= nowIso && endIso >= nowIso;
    });
});

const navbarClass = computed(() => {
  if (isMbkPostseason.value || isBowlWeek.value) {
    return 'short-height';
  }
  if (gamesToday.value) {
    return 'navbar-pad-height';
  }
  return 'navbar-height';
});

const { tvGameResult, tvGameLoading, tvGameError } = useWeekSchedule(sport, year.value, weekInt.value);
</script>

<template>
  <div>
    <template v-if="seasonContentsLoading || tvGameLoading">
      <div class="loading-container">
        <p class="loading-text">Loading Week {{ week }} for {{ paramYear }}</p>
      </div>
    </template>
    <template v-if="seasonContentsError || tvGameError">
      <div class="error-container">
        <p>Sorry. Got a bit of a problem. Let Matt know.</p>
      </div>
    </template>
    <template v-if="seasonContentsResult && tvGameResult">
      <nav role="navigation" :class="`navbar DONTPrint ${navbarClass}`">
        <div class="container">
          <div class="flex-container">
            <div class="flex-row">
              <RouterLink to="/">Home</RouterLink>
            </div>
            <div class="flex-row">
              <RouterLink :to="`/season/${sport}/${paramYear}`">Season Home</RouterLink>
            </div>
            <div v-if="gamesToday" class="flex-row">
              <RouterLink :to="`/schedule/${sport}/daily`">Today's Schedule </RouterLink>
            </div>
          </div>
          <div class="flex-container">
            <div v-if="seasonContentsResult.seasonContents.flexScheduleLink" class="flex-row">
              <RouterLink :to="`/tv-windows/${paramYear}`" target="_blank" rel="noopener"
                >Available TV Windows
              </RouterLink>
            </div>
            <div class="flex-row">
              <RouterLink :to="`/schedule/${sport}/${paramYear}/${week}/text`">Customizable Text-Only Page</RouterLink>
            </div>
          </div>

          <div v-if="!isMbkPostseason && !isBowlWeek" class="flex-container-row pad">
            <template v-if="isWeekOne">
              <div class="flex-row-left">
                <RouterLink :to="{ path: `/schedule/${sport}/${paramYear}/${nextWeek}` }">Next Week</RouterLink>
              </div>
            </template>
            <template v-else>
              <div class="flex-row-left">
                <RouterLink :to="{ path: `/schedule/${sport}/${paramYear}/${previousWeek}` }"
                  >Previous Week
                </RouterLink>
              </div>
              <div v-if="!isNextWeekMbkPostseason && !isNextWeekBowlWeek" class="flex-row-right">
                <RouterLink :to="{ path: `/schedule/${sport}/${paramYear}/${nextWeek}` }">Next Week </RouterLink>
              </div>
            </template>
            <br class="mobilehide" />
          </div>
          <br />
          <div v-if="tvGameResult" class="filters">
            <button
              v-if="!isBowlWeek && !isMbkPostseason"
              id="btnWebGames"
              class="show_hideWeb buttonfont"
              @click="toggleWebExclusives">
              {{ buttonText }}
            </button>
          </div>
        </div>
      </nav>
    </template>
    <template v-if="tvGameResult">
      <WeeklyBase
        :tv-games="tvGameResult.tvGames.tvGames"
        :is-bowl-week="isBowlWeek"
        :is-mbk-postseason="isMbkPostseason"
        :is-daily="false"
        :show-ppv-column="tvGameResult.tvGames.showPPVColumn" />
      <NoTvGames v-if="!isBowlWeek && tvGameResult.tvGames.hasNoTVGames" :sport="sport" :year="year" :week="week" />
      <BackToTop />
      <AdsByGoogle />
      <Copyright />
    </template>
  </div>
</template>

<style scoped>
.show_hideWeb {
  display: inline-block;
}

.navbar {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  z-index: 9999;
  background-color: white;
  padding: 2px 0;
  box-shadow: 0 1px 1px rgba(0, 0, 0, 0.1);
  display: block;
  align-items: center;
}

.navbar-height {
  height: 140px;
}

.navbar-pad-height {
  height: 155px;
}

.short-height {
  height: 69.5px;
}

.container {
  height: 100%;
  max-width: 800px;
  margin: 0 auto;
}

.filters {
  margin: 0;
}

.pad {
  padding: 5px 0;
}

.loading-container,
.error-container {
  min-height: 200px;
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  max-width: 800px;
  margin: 0 auto;
  background: #fff;
  border: 1px solid #eee;
}

.loading-text {
  font-size: 1.2em;
  color: #666;
}

.flex-container {
  display: flex;
  flex-direction: column;
}

.flex-container-row {
  display: flex;
  flex-direction: row;
  justify-content: space-between;
}

.flex-row-left {
  margin-right: 40%;
}

.flex-row-right {
  margin-left: 40%;
}

@media all and (min-width: 641px) {
  .buttonfont {
    font-size: 14px;
  }
}

@media only screen and (max-width: 640px) {
  .short-height {
    height: 39.5px;
  }

  .navbar-pad-height,
  .navbar-height {
    height: 88px;
  }

  .flex-container {
    flex-direction: row;
    padding-bottom: 4px;
  }

  .flex-row {
    padding-right: 10px;
  }

  .flex-row-left {
    margin-right: 30%;
  }

  .flex-row-right {
    margin-left: 30%;
  }

  .blockspan {
    display: block;
    padding-bottom: 3px;
  }

  .mobilehide {
    display: none;
  }

  .buttonfont {
    font-size: 0.9em;
  }

  .navbar {
    padding: 10px 3px;
  }
}
</style>
