// mss-app-react/src/components/weekly/WeekGamesTable.tsx
import type { TvGame } from '#/graphQl.mjs';
import PostseasonMbkEvent from '#weekly/PostseasonMbkEvent.tsx';
import { useWebExclusivesContext } from '#hooks/useWebExclusivesContext.mjs';
import WeekGameRow from '#weekly/WeekGameRow.tsx';
import { DateTime } from 'luxon';
import React, { useMemo } from 'react';
import styles from './WeekGamesTable.module.css';

interface WeekGamesTableProps {
  weekDate: string;
  tvGamesForDate: TvGame[];
  isMbkPostseason: boolean;
  isBowlWeek: boolean;
  showPpvColumn: boolean;
}

const WeekGamesTable: React.FC<WeekGamesTableProps> = ({
  weekDate,
  tvGamesForDate,
  isMbkPostseason,
  isBowlWeek,
  showPpvColumn,
}) => {
  const { isWebGamesHidden } = useWebExclusivesContext();
  // Replicating the computed date string layout formatter
  const formattedDate = useMemo(() => {
    return DateTime.fromISO(weekDate).toFormat('DDDD');
  }, [weekDate]);

  // Evaluate dynamic header showing condition
  const shouldShowPpvHeader = !isBowlWeek && !isMbkPostseason && showPpvColumn;

  return (
    <div>
      <h3>{formattedDate}</h3>
      <table className={styles.noTVTable}>
        <thead>
          <tr className={styles.header}>
            <th scope="col">Game</th>
            <th scope="col">Network</th>
            <th scope="col">Coverage Notes / Network Streaming</th>
            {shouldShowPpvHeader && <th scope="col">PPV</th>}
            <th scope="col">Time</th>
          </tr>
        </thead>
        <tbody>
          {tvGamesForDate.map((tvGame) => {
            const rowKey = `${tvGame.homeTeam}-${tvGame.timeWithOffset}`;
            const isWeb = tvGame.mediaIndicator === 'W';

            const classNames = [];

            if (isWeb) {
              classNames.push(styles.webGame);
            }

            if (isWeb && isWebGamesHidden) {
              classNames.push(styles.hidden);
            }

            return (
              <tr key={rowKey} className={classNames.join(' ')}>
                {isBowlWeek || isMbkPostseason ? (
                  <PostseasonMbkEvent tvGame={tvGame} />
                ) : (
                  <WeekGameRow showPPVColumn={showPpvColumn} tvGame={tvGame} />
                )}
              </tr>
            );
          })}
        </tbody>
      </table>
      <br />
    </div>
  );
};

export default WeekGamesTable;

// mss-app/src/components/weekly/WeekGamesTable.vue
<script setup lang="ts">
import type { TvGame } from '#/graphQl.mjs';
import PostseasonMbkEvent from '#weekly/PostseasonMbkEvent.vue';
import WeekGameRow from '#weekly/WeekGameRow.vue';
import { DateTime } from 'luxon';
import { computed } from 'vue';

const props = defineProps<{
  weekDate: string;
  tvGamesForDate: TvGame[];
  isMbkPostseason: boolean;
  isBowlWeek: boolean;
  showPpvColumn: boolean;
}>();

const { weekDate, tvGamesForDate, isMbkPostseason, isBowlWeek, showPpvColumn } = props;

const formattedDate = computed(() => DateTime.fromISO(weekDate).toFormat('DDDD'));
</script>

<template>
  <div>
    <h3>{{ formattedDate }}</h3>
    <table class="noTVTable">
      <thead>
        <tr class="header">
          <th scope="col">Game</th>
          <th scope="col">Network</th>
          <th scope="col">Coverage Notes / Network Streaming</th>
          <th v-if="!isBowlWeek && !isMbkPostseason && showPpvColumn" scope="col">PPV</th>
          <th scope="col">Time</th>
        </tr>
      </thead>
      <tbody>
        <template v-for="tvGame in tvGamesForDate" :key="`${tvGame.homeTeam}-${tvGame.timeWithOffset}`">
          <tr :class="{ webGame: tvGame.mediaIndicator === 'W' }">
            <template v-if="isBowlWeek || isMbkPostseason">
              <PostseasonMbkEvent :tv-game="tvGame" />
            </template>
            <template v-else>
              <WeekGameRow :show-p-p-v-column="showPpvColumn" :tv-game="tvGame" />
            </template>
          </tr>
        </template>
      </tbody>
    </table>
    <br />
  </div>
</template>

<style scoped>
.webGame {
  display: table-row;
  transition: opacity 0.2s ease-in-out;
}

.webGame[style*='display: none'] {
  opacity: 0;
}

.header {
  text-align: center;
}

.noTVTable {
  background-color: #fff;
  border-color: #fff;
  border-style: ridge;
  border-width: 2px;
  border-spacing: 1px;
  border-collapse: collapse;
  width: 100%;
  max-width: 800px;
  table-layout: auto;
  /* Prevent column width changes */
}
</style>
