// mss-app-react/src/components/weekly/WeeklyBase.tsx
import type { TvGame } from '#/graphQl.mjs';
import { useResetAdsenseHeight } from '#/hooks/useResetAdsenseHeight.mjs';
import { getDateForGame } from '#utils/dateFormatting.mjs';
import WeekGamesTable from '#weekly/WeekGamesTable.tsx';
import React, { useMemo } from 'react';
import styles from './WeeklyBase.module.css';

interface WeeklyBaseProps {
  tvGames: TvGame[];
  isBowlWeek: boolean;
  isMbkPostseason: boolean;
  isDaily: boolean;
  showPpvColumn: boolean;
}

const WeeklyBase: React.FC<WeeklyBaseProps> = ({ tvGames, isBowlWeek, isMbkPostseason, isDaily, showPpvColumn }) => {
  const mainRef = useResetAdsenseHeight();

  const hasValidTime = (game: TvGame): game is TvGame & { timeWithOffset: string } =>
    typeof game.timeWithOffset === 'string';

  // Group games dynamically into an associative map dictionary matching Vue's reducer
  const tvGamesByDate = useMemo(() => {
    if (!tvGames) return {} as Record<string, TvGame[]>;

    return tvGames.filter(hasValidTime).reduce<Record<string, TvGame[]>>((acc, game) => {
      const date = getDateForGame(game.timeWithOffset);
      if (date) {
        acc[date] ??= [];
        acc[date].push(game);
      }
      return acc;
    }, {});
  }, [tvGames]);

  // Extract keys and apply natural sorting order bounds
  const datesList = useMemo(() => {
    return Object.keys(tvGamesByDate).sort();
  }, [tvGamesByDate]);

  if (datesList.length === 0 && !isDaily) {
    return null;
  }

  // Flatten Vue array class checks into a clean text conditional layout string
  const mainPaddingClass =
    isMbkPostseason || isBowlWeek ? styles.shortMainPadding : isDaily ? styles.dailyPadding : styles.mainPadding;

  return (
    <main ref={mainRef} className={mainPaddingClass}>
      <div id="WeeksBase">
        {tvGames.length === 0 ? (
          <p>There are no televised games at this time</p>
        ) : (
          <>
            <p>
              <strong>All start times displayed are based on your device's location.</strong>
            </p>
            {datesList.map((weekDate) => (
              <div key={weekDate}>
                <WeekGamesTable
                  weekDate={weekDate}
                  isBowlWeek={isBowlWeek}
                  isMbkPostseason={isMbkPostseason}
                  showPpvColumn={showPpvColumn}
                  tvGamesForDate={tvGamesByDate[weekDate]}
                />
              </div>
            ))}
          </>
        )}
      </div>
    </main>
  );
};

export default WeeklyBase;

// mss-app/src/components/weekly/WeeklyBase.vue
<script setup lang="ts">
import type { TvGame } from '#/graphQl.mjs';
import WeekGamesTable from '#weekly/WeekGamesTable.vue';
import { DateTime } from 'luxon';
import { computed } from 'vue';

const props = defineProps<{
  tvGames: TvGame[];
  isBowlWeek: boolean;
  isMbkPostseason: boolean;
  isDaily: boolean;
  showPpvColumn: boolean;
}>();

const { tvGames, isBowlWeek, isMbkPostseason, showPpvColumn, isDaily } = props;

const getGameDate = (timeWithOffset: string): string => {
  const eastern = DateTime.fromISO(timeWithOffset).setZone('America/New_York');
  return eastern.toFormat('t') === '12:00 AM'
    ? (eastern.toISODate() ?? '')
    : (DateTime.fromISO(timeWithOffset).toLocal().toISODate() ?? '');
};

const hasValidTime = (game: TvGame): game is TvGame & { timeWithOffset: string } =>
  typeof game.timeWithOffset === 'string';

const tvGamesByDate = computed(() =>
  tvGames.filter(hasValidTime).reduce<Record<string, TvGame[]>>((acc, game) => {
    const date = getGameDate(game.timeWithOffset);
    if (date) {
      acc[date] ??= [];
      acc[date].push(game);
    }
    return acc;
  }, {})
);

const datesList = computed(() => Object.keys(tvGamesByDate.value).sort());
</script>

<template v-if="datesList.length">
  <div
    id="Main"
    v-reset-adsense-height
    :class="[isMbkPostseason || isBowlWeek ? 'short-main-padding' : isDaily ? 'daily-padding' : 'main-padding']">
    <div id="WeeksBase">
      <template v-if="tvGames.length === 0">
        <p>There are no televised games at this time</p>
      </template>
      <template v-else>
        <p>
          <strong>All start times displayed are based on your device's location.</strong>
        </p>
        <div v-for="weekDate in datesList" :key="weekDate">
          <WeekGamesTable
            :week-date="weekDate"
            :is-bowl-week="isBowlWeek"
            :is-mbk-postseason="isMbkPostseason"
            :show-ppv-column="showPpvColumn"
            :tv-games-for-date="tvGamesByDate[weekDate]" />
        </div>
      </template>
    </div>
  </div>
</template>

<style scoped>
.main-padding {
  padding-top: 140px;
}

.daily-padding {
  padding-top: 105px;
}

.short-main-padding {
  padding-top: 79.5px;
}

@media only screen and (max-width: 640px) {
  .main-padding {
    padding-top: 110px;
  }

  .daily-padding {
    padding-top: 85px;
  }

  .short-main-padding {
    padding-top: 59.5px;
  }
}
</style>
