// mss-app/src/components/weekly/PostseasonMbkEvent.vue
<script setup lang="ts">
import type { TvGame } from '@/graphQl';
import { formatNetworkJpgAndCoverage } from '@/utils/image';
import { formatTime } from '@/utils/game';
import { computed } from 'vue';

const props = defineProps<{ tvGame: TvGame; season: string }>();
const { tvGame, season } = props;

const networkHtml = computed(() => (tvGame.networkJpg ? formatNetworkJpgAndCoverage(tvGame.networkJpg, season) : ''));
const coverageHtml = computed(() =>
  tvGame.coverageNotes ? formatNetworkJpgAndCoverage(tvGame.coverageNotes, season) : ''
);
</script>

<template>
  <td class="game">
    <template v-if="tvGame.gameTitle">
      <b
        ><i>{{ tvGame.gameTitle }}</i></b
      ><br />
    </template>
    <template v-if="tvGame.location">
      <template v-if="tvGame.visitingTeam?.length">
        {{ tvGame.visitingTeam[0] }} vs. {{ tvGame.homeTeam![0] }}<br />
      </template>
      (at {{ tvGame.location }})<br />
    </template>
    <template v-else>
      <template v-if="tvGame.visitingTeam?.length">
        {{ tvGame.visitingTeam[0] }} at {{ tvGame.homeTeam![0] }}<br />
      </template>
    </template>
  </td>
  <td class="network" v-html="networkHtml" />
  <td class="coverage" v-html="coverageHtml" />
  <td class="time">
    {{ formatTime(tvGame.timeWithOffset!) }}
  </td>
</template>

<style scoped>
.game {
  width: 270px;
  border: medium solid Gray;
  border-width: thin;
}

.coverage a img,
.network a img {
  border: 0;
}

.network {
  text-align: center;
  border: medium solid Gray;
  border-width: thin;
}

.coverage {
  border: medium solid Gray;
  border-width: thin;
  empty-cells: show;
  text-align: center;
}

.time {
  width: 70px;
  text-align: right;
  border: medium solid Gray;
  border-width: thin;
  padding: 2px;
}

:deep(.linkblock) {
  display: inline-block;
  padding-top: 7px;
  padding-bottom: 2px;
}

@media all and (min-width: 641px) {
  .game {
    padding: 2px;
    width: 245px;
  }

  .network {
    width: 150px;
    padding: 2px;
  }

  .coverage {
    width: 210px;
  }
}

@media only screen and (max-width: 640px) {
  .game {
    padding: 1px;
  }

  .network {
    width: 90px;
    padding: 0;
  }

  .coverage {
    width: 105px;
  }
}
</style>

// mss-app-react/src/components/weekly/PostseasonMbkEvent.tsx
import type { TvGame } from '#/graphQl.mjs';
import { sanitizeHtml } from '#utils/domText.mjs';
import { formatGame, formatTime } from '#utils/game.mjs';
import React from 'react';
import styles from './PostseasonMbkEvent.module.css';

interface PostseasonMbkEventProps {
  tvGame: TvGame;
}

const PostseasonMbkEvent: React.FC<PostseasonMbkEventProps> = ({ tvGame }) => {
  const visitingTeam = tvGame.visitingTeam ?? [];
  const homeTeam = tvGame.homeTeam ?? [];

  const hasVisitingTeams = visitingTeam.length > 0 && visitingTeam[0] !== '';
  const isStandardMatchup = visitingTeam.length === 1 && homeTeam.length === 1 && visitingTeam[0] !== '';

  return (
    <>
      <td className={styles.game}>
        {tvGame.gameTitle && (
          <>
            <span className={styles.gameTitle}>{tvGame.gameTitle}</span>
            <br />
          </>
        )}

        {/* Dynamic Matchup Condition Block */}
        {!hasVisitingTeams ? null : isStandardMatchup ? (
          <>
            {visitingTeam[0]} {tvGame.location ? 'vs.' : 'at'} {homeTeam[0]}
            <br />
          </>
        ) : (
          <div dangerouslySetInnerHTML={{ __html: sanitizeHtml(formatGame(tvGame)) }} />
        )}

        {tvGame.location && <> (at {tvGame.location}) </>}
      </td>

      <td className={styles.network} dangerouslySetInnerHTML={{ __html: sanitizeHtml(tvGame.networkJpg ?? '') }} />

      <td className={styles.coverage} dangerouslySetInnerHTML={{ __html: sanitizeHtml(tvGame.coverageNotes ?? '') }} />

      <td className={styles.time}>{formatTime(tvGame.timeWithOffset!)}</td>
    </>
  );
};

export default PostseasonMbkEvent;
