// mss-app/src/components/noTVGames/NoTvGames.vue
<script setup lang="ts">
import { useNoTvSchedule } from '#composables/useNoTvSchedule.mjs';
import NoTvGamesTable from '#noTv/NoTvGamesTable.vue';
import { DateTime } from 'luxon';
import { ref } from 'vue';

const props = defineProps<{ week: string; year: string }>();
const { week, year } = props;

const { noTvGamesResults, noTvGamesLoading, noTvGamesError, datesList, load } = useNoTvSchedule(week, year);

const showNoTV = ref(false);

const toggleNoTV = async () => {
  await load();
  const button = document.getElementById('btnConferenceGames');
  if (!button) return;
  button.innerText = showNoTV.value ? 'Show Non-Televised Games' : 'Hide Non-Televised Games';
  showNoTV.value = !showNoTV.value;
};
</script>

<template>
  <div>
    <button id="btnConferenceGames" class="show_hideNoTV buttonfont" @click="toggleNoTV">
      Show Non-Televised Games
    </button>
    <br />
    <template v-if="noTvGamesLoading">
      <div class="loading-container">
        <p class="loading-text">Loading Week {{ week }} for {{ year }}</p>
      </div>
    </template>
    <template v-if="noTvGamesError">
      <div class="error-container">
        <p>Sorry. Got a bit of a problem. Let Matt know.</p>
      </div>
    </template>
    <template v-if="showNoTV && noTvGamesResults">
      <div class="slidingNoTVDiv">
        <p v-if="!noTvGamesResults?.noTvGames.length">
          All FBS games scheduled for this week are being televised or shown online
        </p>
        <NoTvGamesTable
          v-for="(noTVDate, index) in datesList"
          :key="index"
          :no-tv-date="noTVDate"
          :no-tv-games-for-date="
            noTvGamesResults?.noTvGames.filter(
              (x: { timeWithOffset: string }) =>
                DateTime.fromISO(x.timeWithOffset).setZone('America/New_York').toISODate() === noTVDate
            ) || []
          " />
        <br />
      </div>
    </template>
  </div>
</template>

<style scoped>
.slidingNoTVDiv {
  padding-top: 10px;
}

.show_hideNoTV {
  display: inline-block;
}

.loading-container,
.error-container {
  min-height: 200px;
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  max-width: 800px;
  margin: 0 auto;
  background: #fff;
  border: 1px solid #eee;
}

.loading-text {
  font-size: 1.2em;
  color: #666;
}

@media only screen and (max-width: 640px) {
  .buttonfont {
    font-size: 0.9em;
  }
}

@media all and (min-width: 641px) {
  .buttonfont {
    font-size: 14px;
  }
}
</style>

// mss-app-react/src/components/noTVGames/NoTvGames.tsx
import { useNoTvSchedule } from '#hooks/index.mjs';
import { DateTime } from 'luxon';
import React, { useCallback, useState } from 'react';
import NoTvGamesTable from './NoTvGamesTable.tsx';

interface Props {
  week: string;
  year: string;
}

const NoTvGames: React.FC<Props> = ({ week, year }) => {
  const { noTvGamesResults, noTvGamesLoading, noTvGamesError, datesList, load } = useNoTvSchedule(week, year);

  const [showNoTV, setShowNoTV] = useState(false);

  const toggleNoTV = useCallback(async () => {
    await load();
    setShowNoTV((prev) => !prev);
  }, [load]);

  return (
    <div>
      <button
        id="btnConferenceGames"
        className="show_hideNoTV buttonfont"
        onClick={toggleNoTV}
        style={{
          display: 'inline-block',
          padding: '8px 12px',
          backgroundColor: '#2196f3',
          color: 'white',
          border: 'none',
          borderRadius: '4px',
          cursor: 'pointer',
          fontSize: '14px'
        }}
      >
        {showNoTV ? 'Hide Non-Televised Games' : 'Show Non-Televised Games'}
      </button>
      <br />
      <br />
      {noTvGamesLoading && (
        <div
          style={{
            minHeight: '200px',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            width: '100%',
            maxWidth: '800px',
            margin: '0 auto',
            background: '#fff',
            border: '1px solid #eee'
          }}
        >
          <p style={{ fontSize: '1.2em', color: '#666' }}>Loading Week {week} for {year}</p>
        </div>
      )}
      {noTvGamesError && (
        <div
          style={{
            minHeight: '200px',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            width: '100%',
            maxWidth: '800px',
            margin: '0 auto',
            background: '#fff',
            border: '1px solid #eee'
          }}
        >
          <p>Sorry. Got a bit of a problem. Let Matt know.</p>
        </div>
      )}
      {showNoTV && noTvGamesResults && (
        <div style={{ paddingTop: '10px' }}>
          {!noTvGamesResults.noTvGames || noTvGamesResults.noTvGames.length === 0 ? (
            <p>All FBS games scheduled for this week are being televised or shown online</p>
          ) : (
            <>
              {datesList.map((noTVDate, index) => {
                const noTVGamesForDate = (noTvGamesResults.noTvGames || []).filter((game: any) => {
                  if (!game.timeWithOffset) return false;
                  const gameDate = DateTime.fromISO(game.timeWithOffset).setZone('America/New_York').toISODate();
                  return gameDate === noTVDate;
                });

                return (
                  <NoTvGamesTable
                    key={index}
                    noTvDate={noTVDate}
                    noTvGamesForDate={noTVGamesForDate}
                  />
                );
              })}
              <br />
            </>
          )}
        </div>
      )}
    </div>
  );
};

export default NoTvGames;
