// mss-app/src/components/SeasonDates.vue
<script setup lang="ts">
import type { WeekInfo } from '@/graphQl';
import { hasBasketballPostseason } from '@/utils';
import { DateTime } from 'luxon';
import WeekLink from '@/components/WeekLink.vue';
import { computed } from 'vue';

const props = defineProps<{
  contents: WeekInfo[];
  sport: string;
  paramYear: string;
  year: string;
}>();

const { contents, sport, paramYear, year } = props;

const lastContent = contents[contents.length - 1];

const filteredContents = computed(() => contents.filter(x => x.postseasonInd === null));
const postseasonContents = computed(() => contents.filter(x => x.postseasonInd));

const getLinkText = (content: WeekInfo) => {
  if (lastContent.week !== content.week) {
    return `Week ${content.week.toString()} - ${DateTime.fromISO(content.startDate, { zone: 'utc' }).toFormat('MMMM dd')} to ${DateTime.fromISO(content.endDate, { zone: 'utc' }).toFormat('MMMM dd')}`;
  }
  return 'Bowl Games';
};

const getPostseasonLinkText = (content: WeekInfo) => {
  if (content.postseasonInd === 'N') {
    return 'NCAA Tournament';
  } else if (content.postseasonInd === 'I') {
    return 'NIT';
  }
  return 'Other Postseason Tournaments';
};
</script>

<template>
  <div v-if="sport === 'football'">
    <template
      v-for="(content, index) in contents"
      :key="index"
    >
      <WeekLink
        :year="paramYear"
        :sport="sport"
        :content="content"
        :link-text="getLinkText(content)"
      />
    </template>
  </div>
  <div v-else-if="sport === 'basketball' && hasBasketballPostseason(year)">
    <template
      v-for="(content, index) in filteredContents"
      :key="index"
    >
      <WeekLink
        :sport="sport"
        :content="content"
        :year="paramYear"
        :link-text="`Week ${content.week.toString()} - ${DateTime.fromISO(content.startDate, { zone: 'utc' }).toFormat('MMMM dd')} to ${DateTime.fromISO(content.endDate, { zone: 'utc' }).toFormat('MMMM dd')}`"
      />
    </template>
    <p v-if="postseasonContents.length">
      <template
        v-for="(content, index) in postseasonContents"
        :key="index"
      >
        <WeekLink
          :sport="sport"
          :year="paramYear"
          :content="content"
          :link-text="getPostseasonLinkText(content)"
        />
      </template>
    </p>
  </div>
  <div v-else>
    <template
      v-for="(content, index) in contents"
      :key="index"
    >
      <WeekLink
        :sport="sport"
        :year="paramYear"
        :content="content"
        :link-text="`Week ${content.week.toString()} - ${DateTime.fromISO(content.startDate, { zone: 'utc' }).toFormat('MMMM dd')} to ${DateTime.fromISO(content.endDate, { zone: 'utc' }).toFormat('MMMM dd')}`"
      />
    </template>
  </div>
</template>

// mss-app-react/src/components/season/SeasonDates.tsx
import type { WeekInfo } from '#/graphQl.mjs';
import WeekLink from '#season/WeekLink.tsx';
import { DateTime } from 'luxon';
import React, { useMemo } from 'react';
interface SeasonDatesProps {
  contents: WeekInfo[];
  sport: string;
  paramYear: string;
  hasBasketballPostseason: boolean;
}

const SeasonDates: React.FC<SeasonDatesProps> = ({ contents, sport, paramYear, hasBasketballPostseason }) => {
  // Guard clause against empty arrays
  if (!contents || contents.length === 0) return null;

  const lastContent = contents[contents.length - 1];

  // Parity logic: Replacing Vue's computed filters
  const filteredContents = useMemo(() => {
    return contents.filter((x) => !x.postseasonInd);
  }, [contents]);

  const postseasonContents = useMemo(() => {
    return contents.filter((x) => x.postseasonInd);
  }, [contents]);

  // Reusable helper to format date ranges cleanly across templates
  const formatDateRangeText = (content: WeekInfo) => {
    const start = DateTime.fromISO(content.startDate, { zone: 'utc' }).toFormat('MMMM dd');
    const end = DateTime.fromISO(content.endDate, { zone: 'utc' }).toFormat('MMMM dd');
    return `Week ${content.week.toString()} - ${start} to ${end}`;
  };

  const getLinkText = (content: WeekInfo) => {
    if (lastContent.week !== content.week) {
      return formatDateRangeText(content);
    }
    return 'Bowl Games';
  };

  const getPostseasonLinkText = (content: WeekInfo) => {
    if (content.postseasonInd === 'N') {
      return 'NCAA Tournament';
    } else if (content.postseasonInd === 'I') {
      return 'NIT';
    }
    return 'Other Postseason Tournaments';
  };

  if (sport === 'football') {
    return (
      <div>
        {contents.map((content) => (
          <WeekLink
            key={`${content.week}-${content.startDate}`}
            year={paramYear}
            sport={sport}
            content={content}
            linkText={getLinkText(content)}
          />
        ))}
      </div>
    );
  }

  if (sport === 'basketball' && hasBasketballPostseason) {
    return (
      <div>
        {filteredContents.map((content) => (
          <WeekLink
            key={`${content.week}-${content.startDate}`}
            sport={sport}
            content={content}
            year={paramYear}
            linkText={formatDateRangeText(content)}
          />
        ))}

        {postseasonContents.length > 0 && (
          <p>
            {postseasonContents.map((content) => (
              <WeekLink
                key={`${content.week}-${content.startDate}`}
                sport={sport}
                year={paramYear}
                content={content}
                linkText={getPostseasonLinkText(content)}
              />
            ))}
          </p>
        )}
      </div>
    );
  }

  return (
    <div>
      {contents.map((content) => (
        <WeekLink
          key={`${content.week}-${content.startDate}`}
          sport={sport}
          year={paramYear}
          content={content}
          linkText={formatDateRangeText(content)}
        />
      ))}
    </div>
  );
};

export default SeasonDates;
